; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-vectorize,simplifycfg -force-target-instruction-cost=1 \
; RUN:     -force-vector-width=2 -force-vector-interleave=1 \
; RUN:     -experimental-keep-uniform-branches < %s | FileCheck %s

define void @test_keep_uniform_condition(
; CHECK-LABEL: define void @test_keep_uniform_condition(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_CONDITION:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH3:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    br i1 [[UNIFORM_CONDITION]], label %[[IF_TRUE2:.*]], label %[[IF_FALSE1:.*]]
; CHECK:       [[IF_FALSE1]]:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr float, ptr [[TMP2]], i32 0
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x float>, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = fmul <2 x float> [[WIDE_LOAD]], [[WIDE_LOAD]]
; CHECK-NEXT:    br label %[[LOOP_LATCH3]]
; CHECK:       [[IF_TRUE2]]:
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x float> poison, float [[TMP7]], i32 0
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x float> [[TMP9]], float [[TMP8]], i32 1
; CHECK-NEXT:    [[TMP11:%.*]] = fadd <2 x float> [[TMP10]], [[TMP10]]
; CHECK-NEXT:    br label %[[LOOP_LATCH3]]
; CHECK:       [[LOOP_LATCH3]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x float> [ [[TMP11]], %[[IF_TRUE2]] ], [ [[TMP4]], %[[IF_FALSE1]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, ptr [[TMP2]], i32 0
; CHECK-NEXT:    store <2 x float> [[VEC_PHI]], ptr [[TMP12]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    br i1 [[UNIFORM_CONDITION]], label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_VAL:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[A_VAL]], [[A_VAL]]
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[B_VAL:%.*]] = load float, ptr [[B_ADDR]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[B_VAL]], [[B_VAL]]
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi float [ [[ADD]], %[[IF_TRUE]] ], [ [[MUL]], %[[IF_FALSE]] ]
; CHECK-NEXT:    store float [[VAL]], ptr [[B_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_condition, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  br i1 %uniform_condition, label %if.true, label %if.false

if.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  %add = fadd float %a.val, %a.val
  br label %loop.latch

if.false:
  %b.val = load float, ptr %b.addr, align 4
  %mul = fmul float %b.val, %b.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %add, %if.true ], [ %mul, %if.false ]
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_keep_uniform_condition_left_bypass(
; CHECK-LABEL: define void @test_keep_uniform_condition_left_bypass(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_CONDITION:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH3:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds float, ptr [[TMP2]], i32 0
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x float>, ptr [[TMP3]], align 4
; CHECK-NEXT:    br i1 [[UNIFORM_CONDITION]], label %[[LOOP_LATCH3]], label %[[IF_FALSE1:.*]]
; CHECK:       [[IF_FALSE1]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr float, ptr [[TMP1]], i32 0
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <2 x float>, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = fmul <2 x float> [[WIDE_LOAD2]], [[WIDE_LOAD2]]
; CHECK-NEXT:    br label %[[LOOP_LATCH3]]
; CHECK:       [[LOOP_LATCH3]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x float> [ [[WIDE_LOAD]], %[[VECTOR_BODY]] ], [ [[TMP5]], %[[IF_FALSE1]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds float, ptr [[TMP1]], i32 0
; CHECK-NEXT:    store <2 x float> [[VEC_PHI]], ptr [[TMP6]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_VAL:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    br i1 [[UNIFORM_CONDITION]], label %[[LOOP_LATCH]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[B_VAL:%.*]] = load float, ptr [[B_ADDR]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[B_VAL]], [[B_VAL]]
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi float [ [[A_VAL]], %[[LOOP_HEADER]] ], [ [[MUL]], %[[IF_FALSE]] ]
; CHECK-NEXT:    store float [[VAL]], ptr [[B_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_condition, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  br i1 %uniform_condition, label %loop.latch, label %if.false

if.false:
  %b.val = load float, ptr %b.addr, align 4
  %mul = fmul float %b.val, %b.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %a.val, %loop.header ], [ %mul, %if.false ]
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_keep_uniform_condition_right_bypass(
; CHECK-LABEL: define void @test_keep_uniform_condition_right_bypass(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_CONDITION:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH2:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    br i1 [[UNIFORM_CONDITION]], label %[[IF_TRUE1:.*]], label %[[LOOP_LATCH2]]
; CHECK:       [[IF_TRUE1]]:
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x float> poison, float [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x float> [[TMP6]], float [[TMP5]], i32 1
; CHECK-NEXT:    [[TMP8:%.*]] = fadd <2 x float> [[TMP7]], [[TMP7]]
; CHECK-NEXT:    br label %[[LOOP_LATCH2]]
; CHECK:       [[LOOP_LATCH2]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x float> [ [[TMP8]], %[[IF_TRUE1]] ], [ zeroinitializer, %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds float, ptr [[TMP9]], i32 0
; CHECK-NEXT:    store <2 x float> [[VEC_PHI]], ptr [[TMP10]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    br i1 [[UNIFORM_CONDITION]], label %[[IF_TRUE:.*]], label %[[LOOP_LATCH]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_VAL:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[A_VAL]], [[A_VAL]]
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi float [ [[ADD]], %[[IF_TRUE]] ], [ 0.000000e+00, %[[LOOP_HEADER]] ]
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    store float [[VAL]], ptr [[B_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_condition, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  br i1 %uniform_condition, label %if.true, label %loop.latch

if.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  %add = fadd float %a.val, %a.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %add, %if.true ], [ 0.0, %loop.header ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_nested_inner_uniform(
; CHECK-LABEL: define void @test_nested_inner_uniform(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[IF_TRUE_JOIN13:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <2 x i64> [ <i64 0, i64 1>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[IF_TRUE_JOIN13]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = urem <2 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP2]], zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = xor <2 x i1> [[TMP3]], splat (i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x i1> [[TMP4]], i32 0
; CHECK-NEXT:    br i1 [[TMP5]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; CHECK:       [[PRED_LOAD_IF]]:
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x float> poison, float [[TMP7]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; CHECK:       [[PRED_LOAD_CONTINUE]]:
; CHECK-NEXT:    [[TMP9:%.*]] = phi <2 x float> [ poison, %[[VECTOR_BODY]] ], [ [[TMP8]], %[[PRED_LOAD_IF]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x i1> [[TMP4]], i32 1
; CHECK-NEXT:    br i1 [[TMP10]], label %[[PRED_LOAD_IF1:.*]], label %[[PRED_LOAD_CONTINUE2:.*]]
; CHECK:       [[PRED_LOAD_IF1]]:
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <2 x float> [[TMP9]], float [[TMP12]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE2]]
; CHECK:       [[PRED_LOAD_CONTINUE2]]:
; CHECK-NEXT:    [[TMP14:%.*]] = phi <2 x float> [ [[TMP9]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP13]], %[[PRED_LOAD_IF1]] ]
; CHECK-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE_TRUE8:.*]], label %[[IF_TRUE_FALSE3:.*]]
; CHECK:       [[IF_TRUE_FALSE3]]:
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <2 x i1> [[TMP3]], i32 0
; CHECK-NEXT:    br i1 [[TMP15]], label %[[PRED_LOAD_IF4:.*]], label %[[PRED_LOAD_CONTINUE5:.*]]
; CHECK:       [[PRED_LOAD_IF4]]:
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[TMP16]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <2 x float> poison, float [[TMP17]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE5]]
; CHECK:       [[PRED_LOAD_CONTINUE5]]:
; CHECK-NEXT:    [[TMP19:%.*]] = phi <2 x float> [ poison, %[[IF_TRUE_FALSE3]] ], [ [[TMP18]], %[[PRED_LOAD_IF4]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = extractelement <2 x i1> [[TMP3]], i32 1
; CHECK-NEXT:    br i1 [[TMP20]], label %[[PRED_LOAD_IF6:.*]], label %[[IF_TRUE_JOIN13]]
; CHECK:       [[PRED_LOAD_IF6]]:
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP22:%.*]] = load float, ptr [[TMP21]], align 4
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <2 x float> [[TMP19]], float [[TMP22]], i32 1
; CHECK-NEXT:    br label %[[IF_TRUE_JOIN13]]
; CHECK:       [[IF_TRUE_TRUE8]]:
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <2 x i1> [[TMP3]], i32 0
; CHECK-NEXT:    br i1 [[TMP24]], label %[[PRED_LOAD_IF9:.*]], label %[[PRED_LOAD_CONTINUE10:.*]]
; CHECK:       [[PRED_LOAD_IF9]]:
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP26:%.*]] = load float, ptr [[TMP25]], align 4
; CHECK-NEXT:    [[TMP27:%.*]] = insertelement <2 x float> poison, float [[TMP26]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE10]]
; CHECK:       [[PRED_LOAD_CONTINUE10]]:
; CHECK-NEXT:    [[TMP28:%.*]] = phi <2 x float> [ poison, %[[IF_TRUE_TRUE8]] ], [ [[TMP27]], %[[PRED_LOAD_IF9]] ]
; CHECK-NEXT:    [[TMP29:%.*]] = extractelement <2 x i1> [[TMP3]], i32 1
; CHECK-NEXT:    br i1 [[TMP29]], label %[[PRED_LOAD_IF11:.*]], label %[[IF_TRUE_JOIN13]]
; CHECK:       [[PRED_LOAD_IF11]]:
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP31:%.*]] = load float, ptr [[TMP30]], align 4
; CHECK-NEXT:    [[TMP32:%.*]] = insertelement <2 x float> [[TMP28]], float [[TMP31]], i32 1
; CHECK-NEXT:    br label %[[IF_TRUE_JOIN13]]
; CHECK:       [[IF_TRUE_JOIN13]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x float> [ [[TMP19]], %[[PRED_LOAD_CONTINUE5]] ], [ [[TMP23]], %[[PRED_LOAD_IF6]] ], [ [[TMP28]], %[[PRED_LOAD_CONTINUE10]] ], [ [[TMP32]], %[[PRED_LOAD_IF11]] ]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <2 x i1> [[TMP4]], <2 x float> [[TMP14]], <2 x float> [[VEC_PHI]]
; CHECK-NEXT:    [[TMP33:%.*]] = fmul <2 x float> [[PREDPHI]], [[PREDPHI]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds float, ptr [[TMP34]], i32 0
; CHECK-NEXT:    store <2 x float> [[TMP33]], ptr [[TMP35]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <2 x i64> [[VEC_IND]], splat (i64 2)
; CHECK-NEXT:    [[TMP36:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP36]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    [[MOD:%.*]] = urem i64 [[I]], 3
; CHECK-NEXT:    [[DIVERGANT_COND:%.*]] = icmp eq i64 [[MOD]], 0
; CHECK-NEXT:    br i1 [[DIVERGANT_COND]], label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE_TRUE:.*]], label %[[IF_TRUE_FALSE:.*]]
; CHECK:       [[IF_TRUE_TRUE]]:
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_LOAD:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_TRUE_FALSE]]:
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B_LOAD:%.*]] = load float, ptr [[B_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[C_ADDR:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[I]]
; CHECK-NEXT:    [[C_LOAD:%.*]] = load float, ptr [[C_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[LOAD:%.*]] = phi float [ [[C_LOAD]], %[[IF_FALSE]] ], [ [[A_LOAD]], %[[IF_TRUE_TRUE]] ], [ [[B_LOAD]], %[[IF_TRUE_FALSE]] ]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[LOAD]], [[LOAD]]
; CHECK-NEXT:    [[D_ADDR:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[I]]
; CHECK-NEXT:    store float [[MUL]], ptr [[D_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_cond, ptr %A, ptr %B, ptr %C, ptr noalias %D) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %mod = urem i64 %i, 3
  %divergant_cond = icmp eq i64 %mod, 0
  br i1 %divergant_cond, label %if.true, label %if.false

if.true:
  br i1 %uniform_cond, label %if.true.true, label %if.true.false

if.true.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.load = load float, ptr %a.addr, align 4
  br label %if.true.join

if.true.false:
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %b.load = load float, ptr %b.addr, align 4
  br label %if.true.join

if.true.join:
  %a.or.b.load = phi float [ %a.load, %if.true.true ], [ %b.load, %if.true.false ]
  br label %loop.latch

if.false:
  %c.addr = getelementptr inbounds float, ptr %C, i64 %i
  %c.load = load float, ptr %c.addr, align 4
  br label %loop.latch

loop.latch:
  %load = phi float [ %a.or.b.load, %if.true.join ], [ %c.load, %if.false ]
  %mul = fmul float %load, %load
  %d.addr = getelementptr inbounds float, ptr %D, i64 %i
  store float %mul, ptr %d.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_nested_outer_uniform(
; CHECK-LABEL: define void @test_nested_outer_uniform(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH9:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <2 x i64> [ <i64 0, i64 1>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH9]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE2:.*]], label %[[IF_FALSE1:.*]]
; CHECK:       [[IF_FALSE1]]:
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x float> poison, float [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x float> [[TMP6]], float [[TMP5]], i32 1
; CHECK-NEXT:    br label %[[LOOP_LATCH9]]
; CHECK:       [[IF_TRUE2]]:
; CHECK-NEXT:    [[TMP8:%.*]] = urem <2 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq <2 x i64> [[TMP8]], zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = xor <2 x i1> [[TMP9]], splat (i1 true)
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x i1> [[TMP10]], i32 0
; CHECK-NEXT:    br i1 [[TMP11]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; CHECK:       [[PRED_LOAD_IF]]:
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[TMP12]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x float> poison, float [[TMP13]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; CHECK:       [[PRED_LOAD_CONTINUE]]:
; CHECK-NEXT:    [[TMP15:%.*]] = phi <2 x float> [ poison, %[[IF_TRUE2]] ], [ [[TMP14]], %[[PRED_LOAD_IF]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <2 x i1> [[TMP10]], i32 1
; CHECK-NEXT:    br i1 [[TMP16]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; CHECK:       [[PRED_LOAD_IF3]]:
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[TMP17]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = insertelement <2 x float> [[TMP15]], float [[TMP18]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; CHECK:       [[PRED_LOAD_CONTINUE4]]:
; CHECK-NEXT:    [[TMP20:%.*]] = phi <2 x float> [ [[TMP15]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP19]], %[[PRED_LOAD_IF3]] ]
; CHECK-NEXT:    [[TMP21:%.*]] = extractelement <2 x i1> [[TMP9]], i32 0
; CHECK-NEXT:    br i1 [[TMP21]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6:.*]]
; CHECK:       [[PRED_LOAD_IF5]]:
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[TMP22]], align 4
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <2 x float> poison, float [[TMP23]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; CHECK:       [[PRED_LOAD_CONTINUE6]]:
; CHECK-NEXT:    [[TMP25:%.*]] = phi <2 x float> [ poison, %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP24]], %[[PRED_LOAD_IF5]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = extractelement <2 x i1> [[TMP9]], i32 1
; CHECK-NEXT:    br i1 [[TMP26]], label %[[PRED_LOAD_IF7:.*]], label %[[PRED_LOAD_CONTINUE8:.*]]
; CHECK:       [[PRED_LOAD_IF7]]:
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP28:%.*]] = load float, ptr [[TMP27]], align 4
; CHECK-NEXT:    [[TMP29:%.*]] = insertelement <2 x float> [[TMP25]], float [[TMP28]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE8]]
; CHECK:       [[PRED_LOAD_CONTINUE8]]:
; CHECK-NEXT:    [[TMP30:%.*]] = phi <2 x float> [ [[TMP25]], %[[PRED_LOAD_CONTINUE6]] ], [ [[TMP29]], %[[PRED_LOAD_IF7]] ]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <2 x i1> [[TMP10]], <2 x float> [[TMP20]], <2 x float> [[TMP30]]
; CHECK-NEXT:    br label %[[LOOP_LATCH9]]
; CHECK:       [[LOOP_LATCH9]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x float> [ [[PREDPHI]], %[[PRED_LOAD_CONTINUE8]] ], [ [[TMP7]], %[[IF_FALSE1]] ]
; CHECK-NEXT:    [[TMP31:%.*]] = fmul <2 x float> [[VEC_PHI]], [[VEC_PHI]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds float, ptr [[TMP32]], i32 0
; CHECK-NEXT:    store <2 x float> [[TMP31]], ptr [[TMP33]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <2 x i64> [[VEC_IND]], splat (i64 2)
; CHECK-NEXT:    [[TMP34:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP34]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[MOD:%.*]] = urem i64 [[I]], 3
; CHECK-NEXT:    [[DIVERGANT_COND:%.*]] = icmp eq i64 [[MOD]], 0
; CHECK-NEXT:    br i1 [[DIVERGANT_COND]], label %[[IF_TRUE_TRUE:.*]], label %[[IF_TRUE_FALSE:.*]]
; CHECK:       [[IF_TRUE_TRUE]]:
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_LOAD:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_TRUE_FALSE]]:
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B_LOAD:%.*]] = load float, ptr [[B_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[C_ADDR:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[I]]
; CHECK-NEXT:    [[C_LOAD:%.*]] = load float, ptr [[C_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[LOAD:%.*]] = phi float [ [[C_LOAD]], %[[IF_FALSE]] ], [ [[A_LOAD]], %[[IF_TRUE_TRUE]] ], [ [[B_LOAD]], %[[IF_TRUE_FALSE]] ]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[LOAD]], [[LOAD]]
; CHECK-NEXT:    [[D_ADDR:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[I]]
; CHECK-NEXT:    store float [[MUL]], ptr [[D_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_cond, ptr %A, ptr %B, ptr %C, ptr noalias %D) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  br i1 %uniform_cond, label %if.true, label %if.false

if.true:
  %mod = urem i64 %i, 3
  %divergant_cond = icmp eq i64 %mod, 0
  br i1 %divergant_cond, label %if.true.true, label %if.true.false

if.true.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.load = load float, ptr %a.addr, align 4
  br label %if.true.join

if.true.false:
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %b.load = load float, ptr %b.addr, align 4
  br label %if.true.join

if.true.join:
  %a.or.b.load = phi float [ %a.load, %if.true.true ], [ %b.load, %if.true.false ]
  br label %loop.latch

if.false:
  %c.addr = getelementptr inbounds float, ptr %C, i64 %i
  %c.load = load float, ptr %c.addr, align 4
  br label %loop.latch

loop.latch:
  %load = phi float [ %a.or.b.load, %if.true.join ], [ %c.load, %if.false ]
  %mul = fmul float %load, %load
  %d.addr = getelementptr inbounds float, ptr %D, i64 %i
  store float %mul, ptr %d.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

; Here, the loop.latch block has three predecessors, and currently,
; this mean that no uniform branches that join in that block can be
; kept (it would require mixing phis and blends, it is possible but
; not yet implemented).
define void @test_no_dedicated_join_block(
; CHECK-LABEL: define void @test_no_dedicated_join_block(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <2 x i1> poison, i1 [[UNIFORM_COND]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <2 x i1> [[BROADCAST_SPLATINSERT]], <2 x i1> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = xor <2 x i1> [[BROADCAST_SPLAT]], splat (i1 true)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_LOAD_CONTINUE10:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <2 x i64> [ <i64 0, i64 1>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_LOAD_CONTINUE10]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i1> [[TMP2]], i32 0
; CHECK-NEXT:    br i1 [[TMP3]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; CHECK:       [[PRED_LOAD_IF]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x float> poison, float [[TMP5]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; CHECK:       [[PRED_LOAD_CONTINUE]]:
; CHECK-NEXT:    [[TMP7:%.*]] = phi <2 x float> [ poison, %[[VECTOR_BODY]] ], [ [[TMP6]], %[[PRED_LOAD_IF]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x i1> [[TMP2]], i32 1
; CHECK-NEXT:    br i1 [[TMP8]], label %[[PRED_LOAD_IF1:.*]], label %[[PRED_LOAD_CONTINUE2:.*]]
; CHECK:       [[PRED_LOAD_IF1]]:
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP9]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> [[TMP7]], float [[TMP10]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE2]]
; CHECK:       [[PRED_LOAD_CONTINUE2]]:
; CHECK-NEXT:    [[TMP12:%.*]] = phi <2 x float> [ [[TMP7]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP11]], %[[PRED_LOAD_IF1]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = urem <2 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq <2 x i64> [[TMP13]], zeroinitializer
; CHECK-NEXT:    [[TMP15:%.*]] = xor <2 x i1> [[TMP14]], splat (i1 true)
; CHECK-NEXT:    [[TMP16:%.*]] = select <2 x i1> [[BROADCAST_SPLAT]], <2 x i1> [[TMP15]], <2 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <2 x i1> [[TMP16]], i32 0
; CHECK-NEXT:    br i1 [[TMP17]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; CHECK:       [[PRED_LOAD_IF3]]:
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP19:%.*]] = load float, ptr [[TMP18]], align 4
; CHECK-NEXT:    [[TMP20:%.*]] = insertelement <2 x float> poison, float [[TMP19]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; CHECK:       [[PRED_LOAD_CONTINUE4]]:
; CHECK-NEXT:    [[TMP21:%.*]] = phi <2 x float> [ poison, %[[PRED_LOAD_CONTINUE2]] ], [ [[TMP20]], %[[PRED_LOAD_IF3]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <2 x i1> [[TMP16]], i32 1
; CHECK-NEXT:    br i1 [[TMP22]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6:.*]]
; CHECK:       [[PRED_LOAD_IF5]]:
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[TMP23]], align 4
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <2 x float> [[TMP21]], float [[TMP24]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; CHECK:       [[PRED_LOAD_CONTINUE6]]:
; CHECK-NEXT:    [[TMP26:%.*]] = phi <2 x float> [ [[TMP21]], %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP25]], %[[PRED_LOAD_IF5]] ]
; CHECK-NEXT:    [[TMP27:%.*]] = select <2 x i1> [[BROADCAST_SPLAT]], <2 x i1> [[TMP14]], <2 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP28:%.*]] = extractelement <2 x i1> [[TMP27]], i32 0
; CHECK-NEXT:    br i1 [[TMP28]], label %[[PRED_LOAD_IF7:.*]], label %[[PRED_LOAD_CONTINUE8:.*]]
; CHECK:       [[PRED_LOAD_IF7]]:
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP30:%.*]] = load float, ptr [[TMP29]], align 4
; CHECK-NEXT:    [[TMP31:%.*]] = insertelement <2 x float> poison, float [[TMP30]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE8]]
; CHECK:       [[PRED_LOAD_CONTINUE8]]:
; CHECK-NEXT:    [[TMP32:%.*]] = phi <2 x float> [ poison, %[[PRED_LOAD_CONTINUE6]] ], [ [[TMP31]], %[[PRED_LOAD_IF7]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = extractelement <2 x i1> [[TMP27]], i32 1
; CHECK-NEXT:    br i1 [[TMP33]], label %[[PRED_LOAD_IF9:.*]], label %[[PRED_LOAD_CONTINUE10]]
; CHECK:       [[PRED_LOAD_IF9]]:
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP35:%.*]] = load float, ptr [[TMP34]], align 4
; CHECK-NEXT:    [[TMP36:%.*]] = insertelement <2 x float> [[TMP32]], float [[TMP35]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE10]]
; CHECK:       [[PRED_LOAD_CONTINUE10]]:
; CHECK-NEXT:    [[TMP37:%.*]] = phi <2 x float> [ [[TMP32]], %[[PRED_LOAD_CONTINUE8]] ], [ [[TMP36]], %[[PRED_LOAD_IF9]] ]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <2 x i1> [[TMP16]], <2 x float> [[TMP26]], <2 x float> [[TMP37]]
; CHECK-NEXT:    [[PREDPHI11:%.*]] = select <2 x i1> [[TMP2]], <2 x float> [[TMP12]], <2 x float> [[PREDPHI]]
; CHECK-NEXT:    [[TMP38:%.*]] = fmul <2 x float> [[PREDPHI11]], [[PREDPHI11]]
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds float, ptr [[TMP39]], i32 0
; CHECK-NEXT:    store <2 x float> [[TMP38]], ptr [[TMP40]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <2 x i64> [[VEC_IND]], splat (i64 2)
; CHECK-NEXT:    [[TMP41:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP41]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[MOD:%.*]] = urem i64 [[I]], 3
; CHECK-NEXT:    [[DIVERGANT_COND:%.*]] = icmp eq i64 [[MOD]], 0
; CHECK-NEXT:    br i1 [[DIVERGANT_COND]], label %[[IF_TRUE_TRUE:.*]], label %[[IF_TRUE_FALSE:.*]]
; CHECK:       [[IF_TRUE_TRUE]]:
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_LOAD:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_TRUE_FALSE]]:
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B_LOAD:%.*]] = load float, ptr [[B_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[C_ADDR:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[I]]
; CHECK-NEXT:    [[C_LOAD:%.*]] = load float, ptr [[C_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[LOAD:%.*]] = phi float [ [[A_LOAD]], %[[IF_TRUE_TRUE]] ], [ [[B_LOAD]], %[[IF_TRUE_FALSE]] ], [ [[C_LOAD]], %[[IF_FALSE]] ]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[LOAD]], [[LOAD]]
; CHECK-NEXT:    [[D_ADDR:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[I]]
; CHECK-NEXT:    store float [[MUL]], ptr [[D_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_cond, ptr %A, ptr %B, ptr %C, ptr noalias %D) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  br i1 %uniform_cond, label %if.true, label %if.false

if.true:
  %mod = urem i64 %i, 3
  %divergant_cond = icmp eq i64 %mod, 0
  br i1 %divergant_cond, label %if.true.true, label %if.true.false

if.true.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.load = load float, ptr %a.addr, align 4
  br label %loop.latch

if.true.false:
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %b.load = load float, ptr %b.addr, align 4
  br label %loop.latch

if.false:
  %c.addr = getelementptr inbounds float, ptr %C, i64 %i
  %c.load = load float, ptr %c.addr, align 4
  br label %loop.latch

loop.latch:
  %load = phi float [ %a.load, %if.true.true ], [ %b.load, %if.true.false ], [ %c.load, %if.false ]
  %mul = fmul float %load, %load
  %d.addr = getelementptr inbounds float, ptr %D, i64 %i
  store float %mul, ptr %d.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

; Here, the two sides of the branch at the head of loop.header do not form
; seperate single-entry single-exit subregions because of a latch from
; if.true.true to if.false.
define void @test_not_single_entry_single_exit(
; CHECK-LABEL: define void @test_not_single_entry_single_exit(
; CHECK-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND1:%.*]], i1 [[UNIFORM_COND2:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT7:%.*]] = insertelement <2 x i1> poison, i1 [[UNIFORM_COND2]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT8:%.*]] = shufflevector <2 x i1> [[BROADCAST_SPLATINSERT7]], <2 x i1> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP27:%.*]] = xor <2 x i1> [[BROADCAST_SPLAT8]], splat (i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <2 x i1> poison, i1 [[UNIFORM_COND1]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <2 x i1> [[BROADCAST_SPLATINSERT1]], <2 x i1> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP29:%.*]] = xor <2 x i1> [[BROADCAST_SPLAT]], splat (i1 true)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_LOAD_CONTINUE12:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <2 x i64> [ <i64 0, i64 1>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_LOAD_CONTINUE12]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = urem <2 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <2 x i64> [[TMP2]], zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = xor <2 x i1> [[TMP3]], splat (i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = select <2 x i1> [[BROADCAST_SPLAT]], <2 x i1> [[TMP4]], <2 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i1> [[TMP5]], i32 0
; CHECK-NEXT:    br i1 [[TMP6]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; CHECK:       [[PRED_LOAD_IF]]:
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x float> poison, float [[TMP8]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; CHECK:       [[PRED_LOAD_CONTINUE]]:
; CHECK-NEXT:    [[TMP10:%.*]] = phi <2 x float> [ poison, %[[VECTOR_BODY]] ], [ [[TMP9]], %[[PRED_LOAD_IF]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x i1> [[TMP5]], i32 1
; CHECK-NEXT:    br i1 [[TMP11]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; CHECK:       [[PRED_LOAD_IF3]]:
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[TMP12]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x float> [[TMP10]], float [[TMP13]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; CHECK:       [[PRED_LOAD_CONTINUE4]]:
; CHECK-NEXT:    [[TMP15:%.*]] = phi <2 x float> [ [[TMP10]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP14]], %[[PRED_LOAD_IF3]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = select <2 x i1> [[BROADCAST_SPLAT]], <2 x i1> [[TMP3]], <2 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <2 x i1> [[TMP16]], i32 0
; CHECK-NEXT:    br i1 [[TMP17]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6:.*]]
; CHECK:       [[PRED_LOAD_IF5]]:
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP19:%.*]] = load float, ptr [[TMP18]], align 4
; CHECK-NEXT:    [[TMP20:%.*]] = insertelement <2 x float> poison, float [[TMP19]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; CHECK:       [[PRED_LOAD_CONTINUE6]]:
; CHECK-NEXT:    [[TMP21:%.*]] = phi <2 x float> [ poison, %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP20]], %[[PRED_LOAD_IF5]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <2 x i1> [[TMP16]], i32 1
; CHECK-NEXT:    br i1 [[TMP22]], label %[[PRED_LOAD_IF7:.*]], label %[[PRED_LOAD_CONTINUE8:.*]]
; CHECK:       [[PRED_LOAD_IF7]]:
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[TMP23]], align 4
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <2 x float> [[TMP21]], float [[TMP24]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE8]]
; CHECK:       [[PRED_LOAD_CONTINUE8]]:
; CHECK-NEXT:    [[TMP26:%.*]] = phi <2 x float> [ [[TMP21]], %[[PRED_LOAD_CONTINUE6]] ], [ [[TMP25]], %[[PRED_LOAD_IF7]] ]
; CHECK-NEXT:    [[TMP28:%.*]] = select <2 x i1> [[TMP16]], <2 x i1> [[TMP27]], <2 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP30:%.*]] = or <2 x i1> [[TMP28]], [[TMP29]]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <2 x i1> [[TMP29]], <2 x float> zeroinitializer, <2 x float> [[TMP26]]
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <2 x i1> [[TMP30]], i32 0
; CHECK-NEXT:    br i1 [[TMP31]], label %[[PRED_LOAD_IF9:.*]], label %[[PRED_LOAD_CONTINUE10:.*]]
; CHECK:       [[PRED_LOAD_IF9]]:
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[TMP32]], align 4
; CHECK-NEXT:    [[TMP34:%.*]] = insertelement <2 x float> poison, float [[TMP33]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE10]]
; CHECK:       [[PRED_LOAD_CONTINUE10]]:
; CHECK-NEXT:    [[TMP35:%.*]] = phi <2 x float> [ poison, %[[PRED_LOAD_CONTINUE8]] ], [ [[TMP34]], %[[PRED_LOAD_IF9]] ]
; CHECK-NEXT:    [[TMP36:%.*]] = extractelement <2 x i1> [[TMP30]], i32 1
; CHECK-NEXT:    br i1 [[TMP36]], label %[[PRED_LOAD_IF11:.*]], label %[[PRED_LOAD_CONTINUE12]]
; CHECK:       [[PRED_LOAD_IF11]]:
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[TMP1]]
; CHECK-NEXT:    [[TMP38:%.*]] = load float, ptr [[TMP37]], align 4
; CHECK-NEXT:    [[TMP39:%.*]] = insertelement <2 x float> [[TMP35]], float [[TMP38]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE12]]
; CHECK:       [[PRED_LOAD_CONTINUE12]]:
; CHECK-NEXT:    [[TMP40:%.*]] = phi <2 x float> [ [[TMP35]], %[[PRED_LOAD_CONTINUE10]] ], [ [[TMP39]], %[[PRED_LOAD_IF11]] ]
; CHECK-NEXT:    [[TMP41:%.*]] = fadd <2 x float> [[TMP40]], [[PREDPHI]]
; CHECK-NEXT:    [[PREDPHI13:%.*]] = select <2 x i1> [[TMP5]], <2 x float> [[TMP15]], <2 x float> [[TMP26]]
; CHECK-NEXT:    [[PREDPHI14:%.*]] = select <2 x i1> [[TMP30]], <2 x float> [[TMP41]], <2 x float> [[PREDPHI13]]
; CHECK-NEXT:    [[TMP42:%.*]] = fmul <2 x float> [[PREDPHI14]], [[PREDPHI14]]
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds float, ptr [[TMP43]], i32 0
; CHECK-NEXT:    store <2 x float> [[TMP42]], ptr [[TMP44]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <2 x i64> [[VEC_IND]], splat (i64 2)
; CHECK-NEXT:    [[TMP45:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP45]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP_HEADER:.*]]
; CHECK:       [[LOOP_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[I_NEXT:%.*]], %[[LOOP_LATCH:.*]] ]
; CHECK-NEXT:    br i1 [[UNIFORM_COND1]], label %[[IF_TRUE:.*]], label %[[IF_FALSE:.*]]
; CHECK:       [[IF_TRUE]]:
; CHECK-NEXT:    [[MOD:%.*]] = urem i64 [[I]], 3
; CHECK-NEXT:    [[DIVERGANT_COND:%.*]] = icmp eq i64 [[MOD]], 0
; CHECK-NEXT:    br i1 [[DIVERGANT_COND]], label %[[IF_TRUE_TRUE:.*]], label %[[IF_TRUE_FALSE:.*]]
; CHECK:       [[IF_TRUE_TRUE]]:
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    [[A_LOAD:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    br i1 [[UNIFORM_COND2]], label %[[LOOP_LATCH]], label %[[IF_FALSE]]
; CHECK:       [[IF_TRUE_FALSE]]:
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B_LOAD:%.*]] = load float, ptr [[B_ADDR]], align 4
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[IF_FALSE]]:
; CHECK-NEXT:    [[A_OR_ZERO:%.*]] = phi float [ [[A_LOAD]], %[[IF_TRUE_TRUE]] ], [ 0.000000e+00, %[[LOOP_HEADER]] ]
; CHECK-NEXT:    [[C_ADDR:%.*]] = getelementptr inbounds float, ptr [[C]], i64 [[I]]
; CHECK-NEXT:    [[C_LOAD:%.*]] = load float, ptr [[C_ADDR]], align 4
; CHECK-NEXT:    [[C_VAL:%.*]] = fadd float [[C_LOAD]], [[A_OR_ZERO]]
; CHECK-NEXT:    br label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi float [ [[C_VAL]], %[[IF_FALSE]] ], [ [[A_LOAD]], %[[IF_TRUE_TRUE]] ], [ [[B_LOAD]], %[[IF_TRUE_FALSE]] ]
; CHECK-NEXT:    [[MUL:%.*]] = fmul float [[VAL]], [[VAL]]
; CHECK-NEXT:    [[D_ADDR:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[I]]
; CHECK-NEXT:    store float [[MUL]], ptr [[D_ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT]], label %[[LOOP_HEADER]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
  i64 %N, i1 %uniform_cond1, i1 %uniform_cond2, ptr %A, ptr %B, ptr %C, ptr noalias %D) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  br i1 %uniform_cond1, label %if.true, label %if.false

if.true:
  %mod = urem i64 %i, 3
  %divergant_cond = icmp eq i64 %mod, 0
  br i1 %divergant_cond, label %if.true.true, label %if.true.false

if.true.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.load = load float, ptr %a.addr, align 4
  br i1 %uniform_cond2, label %if.true.join, label %if.false

if.true.false:
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %b.load = load float, ptr %b.addr, align 4
  br label %if.true.join

if.true.join:
  %a.or.b.load = phi float [ %a.load, %if.true.true ], [ %b.load, %if.true.false ]
  br label %loop.latch

if.false:
  %a.or.zero = phi float [ %a.load, %if.true.true ], [ 0.0, %loop.header ]
  %c.addr = getelementptr inbounds float, ptr %C, i64 %i
  %c.load = load float, ptr %c.addr, align 4
  %c.val = fadd float %c.load, %a.or.zero
  br label %loop.latch

loop.latch:
  %val = phi float [ %a.or.b.load, %if.true.join ], [ %c.val, %if.false ]
  %mul = fmul float %val, %val
  %d.addr = getelementptr inbounds float, ptr %D, i64 %i
  store float %mul, ptr %d.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META2]], [[META1]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META1]], [[META2]]}
; CHECK: [[LOOP9]] = distinct !{[[LOOP9]], [[META2]], [[META1]]}
; CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META1]], [[META2]]}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META2]], [[META1]]}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META1]], [[META2]]}
; CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META2]], [[META1]]}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META1]], [[META2]]}
; CHECK: [[LOOP15]] = distinct !{[[LOOP15]], [[META2]], [[META1]]}
;.
