; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes='loop-mssa(licm),gvn' -licm-use-parallel-access-md=false -S | FileCheck %s -check-prefix=CHECK_REF
; RUN: opt < %s -passes='loop-mssa(licm),gvn' -licm-use-parallel-access-md=true -S | FileCheck %s -check-prefix=CHECK_OPT

define void @foo(i64 %N, ptr %A, ptr %B, ptr %C) {
; CHECK_REF-LABEL: define void @foo(
; CHECK_REF-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK_REF-NEXT:  [[ENTRY:.*]]:
; CHECK_REF-NEXT:    br label %[[LOOP:.*]]
; CHECK_REF:       [[LOOP]]:
; CHECK_REF-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK_REF-NEXT:    [[HOISTABLE:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0:![0-9]+]]
; CHECK_REF-NEXT:    [[SUM:%.*]] = add i32 [[HOISTABLE]], 42
; CHECK_REF-NEXT:    store i32 [[SUM]], ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[B_GEP:%.*]] = getelementptr i32, ptr [[B]], i64 [[I]]
; CHECK_REF-NEXT:    [[B_VAL:%.*]] = load i32, ptr [[B_GEP]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[B_NEW:%.*]] = add i32 [[B_VAL]], 123
; CHECK_REF-NEXT:    store i32 [[B_NEW]], ptr [[B_GEP]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK_REF-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK_REF-NEXT:    br i1 [[EXITCOND]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP1:![0-9]+]]
; CHECK_REF:       [[EXIT]]:
; CHECK_REF-NEXT:    ret void
;
; CHECK_OPT-LABEL: define void @foo(
; CHECK_OPT-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK_OPT-NEXT:  [[ENTRY:.*]]:
; CHECK_OPT-NEXT:    [[A_PROMOTED:%.*]] = load i32, ptr [[A]], align 4
; CHECK_OPT-NEXT:    br label %[[LOOP:.*]]
; CHECK_OPT:       [[LOOP]]:
; CHECK_OPT-NEXT:    [[SUM1:%.*]] = phi i32 [ [[SUM:%.*]], %[[LOOP]] ], [ [[A_PROMOTED]], %[[ENTRY]] ]
; CHECK_OPT-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK_OPT-NEXT:    [[SUM]] = add i32 [[SUM1]], 42
; CHECK_OPT-NEXT:    [[B_GEP:%.*]] = getelementptr i32, ptr [[B]], i64 [[I]]
; CHECK_OPT-NEXT:    [[B_VAL:%.*]] = load i32, ptr [[B_GEP]], align 4, !alias.scope [[META0:![0-9]+]], !llvm.access.group [[ACC_GRP3:![0-9]+]]
; CHECK_OPT-NEXT:    [[B_NEW:%.*]] = add i32 [[B_VAL]], 123
; CHECK_OPT-NEXT:    store i32 [[B_NEW]], ptr [[B_GEP]], align 4, !alias.scope [[META0]], !noalias [[META4:![0-9]+]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK_OPT-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK_OPT-NEXT:    br i1 [[EXITCOND]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK_OPT:       [[EXIT]]:
; CHECK_OPT-NEXT:    store i32 [[SUM]], ptr [[A]], align 4, !noalias [[META0]]
; CHECK_OPT-NEXT:    ret void
;
entry:
  br label %loop
loop:
  %i = phi i64 [ %i.next, %loop ], [ 0, %entry ]
  ; A "reduction": The loaded-from/stored-to address is invariant, and so
  ; the load can be hoisted and the store can be sunken and the sum
  ; could be replaced by a PHI.
  %hoistable = load i32, ptr %A, align 4, !llvm.access.group !3
  %sum = add i32 %hoistable, 42
  store i32 %sum, ptr %A, align 4, !llvm.access.group !3
  ; Access that cannot be hoisted, but that could alias with the invariant
  ; accesses above would it not be for the llvm.access.group MD.
  %b.gep = getelementptr i32, ptr %B, i64 %i
  %b.val = load i32, ptr %b.gep, align 4, !llvm.access.group !3
  %b.new = add i32 %b.val, 123
  store i32 %b.new, ptr %b.gep, align 4, !llvm.access.group !3
  %i.next = add nuw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %N
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !1
exit:
  ret void
}

define void @bar(i64 %N, ptr %A, ptr %B, ptr %C) {
; CHECK_REF-LABEL: define void @bar(
; CHECK_REF-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK_REF-NEXT:  [[ENTRY:.*]]:
; CHECK_REF-NEXT:    br label %[[LOOP:.*]]
; CHECK_REF:       [[LOOP]]:
; CHECK_REF-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK_REF-NEXT:    store i64 [[I]], ptr [[C]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[NOT_HOISTABLE:%.*]] = load i64, ptr [[B]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[I]]
; CHECK_REF-NEXT:    [[A_VAL:%.*]] = load i64, ptr [[A_GEP]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[ADD:%.*]] = add i64 [[A_VAL]], [[NOT_HOISTABLE]]
; CHECK_REF-NEXT:    store i64 [[ADD]], ptr [[A_GEP]], align 8, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK_REF-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK_REF-NEXT:    br i1 [[EXITCOND]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP1]]
; CHECK_REF:       [[EXIT]]:
; CHECK_REF-NEXT:    ret void
;
; CHECK_OPT-LABEL: define void @bar(
; CHECK_OPT-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK_OPT-NEXT:  [[ENTRY:.*]]:
; CHECK_OPT-NEXT:    br label %[[LOOP:.*]]
; CHECK_OPT:       [[LOOP]]:
; CHECK_OPT-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK_OPT-NEXT:    store i64 [[I]], ptr [[C]], align 8, !noalias [[META8:![0-9]+]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[NOT_HOISTABLE:%.*]] = load i64, ptr [[B]], align 8, !alias.scope [[META11:![0-9]+]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[I]]
; CHECK_OPT-NEXT:    [[A_VAL:%.*]] = load i64, ptr [[A_GEP]], align 8, !alias.scope [[META8]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[ADD:%.*]] = add i64 [[A_VAL]], [[NOT_HOISTABLE]]
; CHECK_OPT-NEXT:    store i64 [[ADD]], ptr [[A_GEP]], align 8, !alias.scope [[META8]], !noalias [[META11]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK_OPT-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK_OPT-NEXT:    br i1 [[EXITCOND]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6]]
; CHECK_OPT:       [[EXIT]]:
; CHECK_OPT-NEXT:    ret void
;
entry:
  br label %loop
loop:
  %i = phi i64 [ %i.next, %loop ], [ 0, %entry ]
  ; This load should not be hoisted even with the parallel access MD because
  ; the store to %C could alias with it, and this is not a iteration-dependent
  ; aliasing risk.
  store i64 %i, ptr %C, align 8, !llvm.access.group !3
  %not.hoistable = load i64, ptr %B, align 8, !llvm.access.group !3
  %a.gep = getelementptr inbounds i64, ptr %A, i64 %i
  %a.val = load i64, ptr %a.gep, align 8, !llvm.access.group !3
  %add = add i64 %a.val, %not.hoistable
  store i64 %add, ptr %a.gep, align 8, !llvm.access.group !3
  %i.next = add nuw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %N
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !1
exit:
  ret void
}

; Note: This is done by GVN, not LICM! It is LICM that adds the noalias
; MD though as of now.
define void @baz(i64 %N, ptr %A, ptr %B, ptr %C) {
; CHECK_REF-LABEL: define void @baz(
; CHECK_REF-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK_REF-NEXT:  [[ENTRY:.*]]:
; CHECK_REF-NEXT:    br label %[[LOOP:.*]]
; CHECK_REF:       [[LOOP]]:
; CHECK_REF-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK_REF-NEXT:    [[HOISTABLE:%.*]] = load i32, ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[SUM:%.*]] = add i32 [[HOISTABLE]], 42
; CHECK_REF-NEXT:    store i32 [[SUM]], ptr [[A]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[C_VAL:%.*]] = load i32, ptr [[C]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[B_GEP:%.*]] = getelementptr i32, ptr [[B]], i64 [[I]]
; CHECK_REF-NEXT:    [[B_VAL:%.*]] = load i32, ptr [[B_GEP]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[B_NEW:%.*]] = add i32 [[B_VAL]], [[C_VAL]]
; CHECK_REF-NEXT:    store i32 [[B_NEW]], ptr [[B_GEP]], align 4, !llvm.access.group [[ACC_GRP0]]
; CHECK_REF-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK_REF-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK_REF-NEXT:    br i1 [[EXITCOND]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP1]]
; CHECK_REF:       [[EXIT]]:
; CHECK_REF-NEXT:    ret void
;
; CHECK_OPT-LABEL: define void @baz(
; CHECK_OPT-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK_OPT-NEXT:  [[ENTRY:.*]]:
; CHECK_OPT-NEXT:    [[HOISTABLE_PRE:%.*]] = load i32, ptr [[A]], align 4, !alias.scope [[META13:![0-9]+]]
; CHECK_OPT-NEXT:    br label %[[LOOP:.*]]
; CHECK_OPT:       [[LOOP]]:
; CHECK_OPT-NEXT:    [[HOISTABLE:%.*]] = phi i32 [ [[SUM:%.*]], %[[LOOP]] ], [ [[HOISTABLE_PRE]], %[[ENTRY]] ]
; CHECK_OPT-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK_OPT-NEXT:    [[SUM]] = add i32 [[HOISTABLE]], 42
; CHECK_OPT-NEXT:    store i32 [[SUM]], ptr [[A]], align 4, !noalias [[META16:![0-9]+]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[C_VAL:%.*]] = load i32, ptr [[C]], align 4, !alias.scope [[META13]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[B_GEP:%.*]] = getelementptr i32, ptr [[B]], i64 [[I]]
; CHECK_OPT-NEXT:    [[B_VAL:%.*]] = load i32, ptr [[B_GEP]], align 4, !alias.scope [[META16]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[B_NEW:%.*]] = add i32 [[B_VAL]], [[C_VAL]]
; CHECK_OPT-NEXT:    store i32 [[B_NEW]], ptr [[B_GEP]], align 4, !alias.scope [[META16]], !noalias [[META13]], !llvm.access.group [[ACC_GRP3]]
; CHECK_OPT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK_OPT-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK_OPT-NEXT:    br i1 [[EXITCOND]], label %[[EXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP6]]
; CHECK_OPT:       [[EXIT]]:
; CHECK_OPT-NEXT:    ret void
;
entry:
  br label %loop
loop:
  %i = phi i64 [ %i.next, %loop ], [ 0, %entry ]
  ; A "reduction": The loaded-from/stored-to address is invariant, and so
  ; the load can be hoisted. The store cannot be sunken and must stay
  ; because the read from %C could see it!
  %hoistable = load i32, ptr %A, align 4, !llvm.access.group !3
  %sum = add i32 %hoistable, 42
  store i32 %sum, ptr %A, align 4, !llvm.access.group !3
  ; Access that cannot be hoisted, but that could alias with the invariant
  ; accesses above would it not be for the llvm.access.group MD.
  %c.val = load i32, ptr %C, align 4, !llvm.access.group !3
  %b.gep = getelementptr i32, ptr %B, i64 %i
  %b.val = load i32, ptr %b.gep, align 4, !llvm.access.group !3
  %b.new = add i32 %b.val, %c.val
  store i32 %b.new, ptr %b.gep, align 4, !llvm.access.group !3
  %i.next = add nuw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %N
  br i1 %exitcond, label %exit, label %loop, !llvm.loop !1
exit:
  ret void
}

!1 = distinct !{!1, !2}
!2 = !{!"llvm.loop.parallel_accesses", !3}
!3 = distinct !{}
;.
; CHECK_REF: [[ACC_GRP0]] = distinct !{}
; CHECK_REF: [[LOOP1]] = distinct !{[[LOOP1]], [[META2:![0-9]+]]}
; CHECK_REF: [[META2]] = !{!"llvm.loop.parallel_accesses", [[ACC_GRP0]]}
;.
; CHECK_OPT: [[META0]] = !{[[META1:![0-9]+]]}
; CHECK_OPT: [[META1]] = distinct !{[[META1]], [[META2:![0-9]+]], !"foo.loop.scope."}
; CHECK_OPT: [[META2]] = distinct !{[[META2]], !"foo.loop.noalias.scope.domain"}
; CHECK_OPT: [[ACC_GRP3]] = distinct !{}
; CHECK_OPT: [[META4]] = !{[[META5:![0-9]+]]}
; CHECK_OPT: [[META5]] = distinct !{[[META5]], [[META2]], !"foo.loop.scope."}
; CHECK_OPT: [[LOOP6]] = distinct !{[[LOOP6]], [[META7:![0-9]+]]}
; CHECK_OPT: [[META7]] = !{!"llvm.loop.parallel_accesses", [[ACC_GRP3]]}
; CHECK_OPT: [[META8]] = !{[[META9:![0-9]+]]}
; CHECK_OPT: [[META9]] = distinct !{[[META9]], [[META10:![0-9]+]], !"bar.loop.scope."}
; CHECK_OPT: [[META10]] = distinct !{[[META10]], !"bar.loop.noalias.scope.domain"}
; CHECK_OPT: [[META11]] = !{[[META12:![0-9]+]]}
; CHECK_OPT: [[META12]] = distinct !{[[META12]], [[META10]], !"bar.loop.scope."}
; CHECK_OPT: [[META13]] = !{[[META14:![0-9]+]]}
; CHECK_OPT: [[META14]] = distinct !{[[META14]], [[META15:![0-9]+]], !"baz.loop.scope."}
; CHECK_OPT: [[META15]] = distinct !{[[META15]], !"baz.loop.noalias.scope.domain"}
; CHECK_OPT: [[META16]] = !{[[META17:![0-9]+]]}
; CHECK_OPT: [[META17]] = distinct !{[[META17]], [[META15]], !"baz.loop.scope."}
;.
