include:
  - local: '.ci/sipearl-ci-templates.yml'

# Reuseable rules for branch-specific pipelines:

# -----[ Jobs ]----- #

check-formating:
  extends: ['.check-formating']
  allow_failure: true
  rules:
    - when: always

build-x86_64-llvm-aarch64:
  extends: ['.build-llvm', '.common-x86_64']
  variables:
    LIT_TEST_DIRS: "test test/Unit"
    TARGET_TRIPLE: 'aarch64-linux-gnu'
    SYSROOT: "/workspace/sipearl/tools/sysroots/debian-11.0.0-arm64"
  rules:
    - when: always

deploy-x86_64-llvm-aarch64:
  extends:     ['.deploy-llvm', '.common-x86_64']
  needs:       ['build-x86_64-llvm-aarch64']
  variables:
      SLURM_DEPENDENCIES_JOB: 'build-x86_64-llvm-aarch64'
      TARGET_TRIPLE: 'aarch64-linux-gnu'
      SYSROOT: "/workspace/sipearl/tools/sysroots/debian-11.0.0-arm64"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "sipearl" || $CI_COMMIT_BRANCH =~ /^release.*$/)
      when: always
    - when: manual

build-x86_64-llvm-x86_64:
  extends: ['.build-llvm', '.common-x86_64']
  variables:
    LIT_TEST_DIRS: "test test/Unit"
    TARGET_TRIPLE: x86_64-pc-linux-gnu
    SYSROOT: "native"
  rules:
    - when: always

llvm-x86_64-test-suite-x86_64:
  extends: ['.llvm-test-suite', '.common-x86_64']
  needs: ['build-x86_64-llvm-x86_64']
  rules:
    - when: always

  variables:
    SLURM_DEPENDENCIES_JOB: 'build-x86_64-llvm-x86_64'
    TARGET_TRIPLE: x86_64-pc-linux-gnu
    SYSROOT: "native"

deploy-x86_64-llvm-x86_64:
  extends:     ['.deploy-llvm', '.common-x86_64']
  needs:       ['llvm-x86_64-test-suite-x86_64']
  variables:
      SLURM_DEPENDENCIES_JOB: 'build-x86_64-llvm-x86_64'
      TARGET_TRIPLE: x86_64-pc-linux-gnu
      SYSROOT: "native"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "sipearl" || $CI_COMMIT_BRANCH =~ /^release.*$/)
      when: always
    - when: manual

build-aarch64-llvm-aarch64:
  extends: ['.build-llvm', '.common-aarch64']
  variables:
    TARGET_TRIPLE: 'aarch64-linux-gnu'
    SYSROOT: 'native'
    LIT_TEST_DIRS: "test test/Unit"
  rules:
  # Remove this when ampere come back to life
    - when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: ($SIPEARL_TEST_TARGET == null || $SIPEARL_TEST_TARGET == "aarch64")

llvm-aarch64-test-suite-aarch64:
  extends: ['.llvm-test-suite', '.common-aarch64']
  needs: ['build-aarch64-llvm-aarch64']
  rules:
  # Remove this when ampere come back to life
    - when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: ($SIPEARL_TEST_TARGET == null || $SIPEARL_TEST_TARGET == "aarch64")

  variables:
    SLURM_DEPENDENCIES_JOB: 'build-aarch64-llvm-aarch64'
    TARGET_TRIPLE: 'aarch64-linux-gnu'
    SYSROOT: 'native'

deploy-aarch64-llvm-aarch64:
  extends:     ['.deploy-llvm', '.common-aarch64']
  needs:       ['llvm-aarch64-test-suite-aarch64']
  variables:
      SLURM_DEPENDENCIES_JOB: 'llvm-aarch64-test-suite-aarch64'
      TARGET_TRIPLE: 'aarch64-linux-gnu'
      SYSROOT: "native"
  rules:
    - when: never
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "sipearl" || $CI_COMMIT_BRANCH =~ /^release.*$/)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: ($SIPEARL_TEST_TARGET == null || $SIPEARL_TEST_TARGET == "aarch64")
      when: always
    - when: manual

