; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S "-passes=loop(loop-simplifycfg),simplifycfg,dce" -verify-loop-info -verify-dom-info -verify-loop-lcssa < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128-ni:1"

; A test for the simplest case: A stop-if-true PHI of type i1.
define i32 @test1(ptr %A, ptr %B) {
; CHECK-LABEL: define i32 @test1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[B_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[B_GEP]], align 4
; CHECK-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i32 [[B]], ptr [[A_GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[B]], 42
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], 10
; CHECK-NEXT:    [[TMP0:%.*]] = or i1 [[EXITCOND]], [[CMP]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[EXIT:%.*]], label [[LOOP_HEADER]]
; CHECK:       exit:
; CHECK-NEXT:    [[B_LAST_LCSSA:%.*]] = phi i32 [ [[B]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    ret i32 [[B_LAST_LCSSA]]
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %done = phi i1 [ false, %entry ], [ %done.next, %loop.latch ]
  %b.prev = phi i32 [ -1, %entry ], [ %b.last, %loop.latch ]
  br i1 %done, label %loop.latch, label %if.then

if.then:
  %b.gep = getelementptr inbounds i32, ptr %B, i64 %i
  %b = load i32, ptr %b.gep, align 4
  %a.gep = getelementptr inbounds i32, ptr %A, i64 %i
  store i32 %b, ptr %a.gep, align 4
  %cmp = icmp sgt i32 %b, 42
  br label %loop.latch

loop.latch:
  %done.next = phi i1 [ %done, %loop.header ], [ %cmp, %if.then ]
  %b.last = phi i32 [ %b.prev, %loop.header ], [ %b, %if.then ]
  %i.next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, 10
  br i1 %exitcond, label %exit, label %loop.header

exit:
  ret i32 %b.last
}

; A test where the loop must continue as long as the PHI of type i1 is true.
define void @test2(ptr %A, ptr %B) {
; CHECK-LABEL: define void @test2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[B_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[B_GEP]], align 4
; CHECK-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i32 [[B]], ptr [[A_GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[B]], 42
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], 10
; CHECK-NEXT:    [[GOON_NEXT_NOT:%.*]] = xor i1 [[CMP]], true
; CHECK-NEXT:    [[TMP0:%.*]] = or i1 [[EXITCOND]], [[GOON_NEXT_NOT]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[EXIT:%.*]], label [[LOOP_HEADER]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %goon = phi i1 [ true, %entry ], [ %goon.next, %loop.latch ]
  br i1 %goon, label %if.then, label %loop.latch

if.then:
  %b.gep = getelementptr inbounds i32, ptr %B, i64 %i
  %b = load i32, ptr %b.gep, align 4
  %a.gep = getelementptr inbounds i32, ptr %A, i64 %i
  store i32 %b, ptr %a.gep, align 4
  %cmp = icmp sgt i32 %b, 42
  br label %loop.latch

loop.latch:
  %goon.next = phi i1 [ %goon, %loop.header ], [ %cmp, %if.then ]
  %i.next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, 10
  br i1 %exitcond, label %exit, label %loop.header

exit:
  ret void
}

; Yet another variation: This time the backedge conditon of loop
; is different (inner if is entered if PHI is true).
define void @test3(ptr %A, ptr %B) {
; CHECK-LABEL: define void @test3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[B_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[B_GEP]], align 4
; CHECK-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i32 [[B]], ptr [[A_GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[B]], 42
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[CONTINUECOND:%.*]] = icmp ne i64 [[I_NEXT]], 10
; CHECK-NEXT:    [[DONE_NEXT_NOT:%.*]] = xor i1 [[CMP]], true
; CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[CONTINUECOND]], [[DONE_NEXT_NOT]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[LOOP_HEADER]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %done = phi i1 [ false, %entry ], [ %done.next, %loop.latch ]
  br i1 %done, label %loop.latch, label %if.then

if.then:
  %b.gep = getelementptr inbounds i32, ptr %B, i64 %i
  %b = load i32, ptr %b.gep, align 4
  %a.gep = getelementptr inbounds i32, ptr %A, i64 %i
  store i32 %b, ptr %a.gep, align 4
  %cmp = icmp sgt i32 %b, 42
  br label %loop.latch

loop.latch:
  %done.next = phi i1 [ %done, %loop.header ], [ %cmp, %if.then ]
  %i.next = add nuw nsw i64 %i, 1
  %continuecond = icmp ne i64 %i.next, 10
  br i1 %continuecond, label %loop.header, label %exit

exit:
  ret void
}

; And a final variation of the pattern tested above:
define void @test4(ptr %A, ptr %B) {
; CHECK-LABEL: define void @test4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[B_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[B_GEP]], align 4
; CHECK-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i32 [[B]], ptr [[A_GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[B]], 42
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[CONTINUECOND:%.*]] = icmp ne i64 [[I_NEXT]], 10
; CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[CONTINUECOND]], [[CMP]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[LOOP_HEADER]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %goon = phi i1 [ true, %entry ], [ %goon.next, %loop.latch ]
  br i1 %goon, label %if.then, label %loop.latch

if.then:
  %b.gep = getelementptr inbounds i32, ptr %B, i64 %i
  %b = load i32, ptr %b.gep, align 4
  %a.gep = getelementptr inbounds i32, ptr %A, i64 %i
  store i32 %b, ptr %a.gep, align 4
  %cmp = icmp sgt i32 %b, 42
  br label %loop.latch

loop.latch:
  %goon.next = phi i1 [ %goon, %loop.header ], [ %cmp, %if.then ]
  %i.next = add nuw nsw i64 %i, 1
  %continuecond = icmp ne i64 %i.next, 10
  br i1 %continuecond, label %loop.header, label %exit

exit:
  ret void
}

; A pattern already tested, but with a PHI that has type i32 instead of i1.
define void @test5(ptr %A, ptr %B) {
; CHECK-LABEL: define void @test5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[B_GEP:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[I]]
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[B_GEP]], align 4
; CHECK-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i32 [[B]], ptr [[A_GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[B]], 42
; CHECK-NEXT:    [[CMP_ZEXT:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[CONTINUECOND:%.*]] = icmp ne i64 [[I_NEXT]], 10
; CHECK-NEXT:    [[GOON_NEXT_AS_I1:%.*]] = icmp ne i32 [[CMP_ZEXT]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[CONTINUECOND]], [[GOON_NEXT_AS_I1]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[LOOP_HEADER]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %goon = phi i32 [ 1, %entry ], [ %goon.next, %loop.latch ]
  %goon.not = icmp eq i32 %goon, 0
  br i1 %goon.not, label %loop.latch, label %if.then

if.then:
  %b.gep = getelementptr inbounds i32, ptr %B, i64 %i
  %b = load i32, ptr %b.gep, align 4
  %a.gep = getelementptr inbounds i32, ptr %A, i64 %i
  store i32 %b, ptr %a.gep, align 4
  %cmp = icmp sgt i32 %b, 42
  %cmp.zext = zext i1 %cmp to i32
  br label %loop.latch

loop.latch:
  %goon.next = phi i32 [ %goon, %loop.header ], [ %cmp.zext, %if.then ]
  %i.next = add nuw nsw i64 %i, 1
  %continuecond = icmp ne i64 %i.next, 10
  br i1 %continuecond, label %loop.header, label %exit

exit:
  ret void
}

; Here, two loops share the same latch (for.cond.cleanup67), and the LCSSA
; PHI in is a live-out to the inner one because it is used in the header
; of the outer loop (while beeing in its latch, because the latches are the
; same). This makes it look like it could be a feedthrough PHI but it really
; is not!
define void @bug_from_20240606(i1 %cmp66156) personality ptr null {
; CHECK-LABEL: define void @bug_from_20240606(
; CHECK-SAME: i1 [[CMP66156:%.*]]) personality ptr null {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[ICOL_0168:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[SPEC_SELECT:%.*]], [[FOR_COND65_PREHEADER:%.*]] ]
; CHECK-NEXT:    br label [[FOR_COND65_PREHEADER]]
; CHECK:       for.cond65.preheader:
; CHECK-NEXT:    [[SPEC_SELECT]] = select i1 [[CMP66156]], i32 0, i32 [[ICOL_0168]]
; CHECK-NEXT:    [[EXITCOND183_NOT:%.*]] = icmp eq i64 0, 0
; CHECK-NEXT:    br i1 [[EXITCOND183_NOT]], label [[FOR_BODY]], label [[FOR_COND65_PREHEADER]]
;
entry:
  br label %for.body

for.body:                                         ; preds = %for.cond.cleanup67, %entry
  %icol.0168 = phi i32 [ 0, %entry ], [ %icol.2.lcssa, %for.cond.cleanup67 ]
  br label %for.cond65.preheader

for.cond65.preheader:                             ; preds = %for.cond.cleanup67, %for.body
  br i1 %cmp66156, label %for.body68.lr.ph, label %for.cond.cleanup67

for.body68.lr.ph:                                 ; preds = %for.cond65.preheader
  br label %for.cond.cleanup67

for.cond.cleanup67:                               ; preds = %for.body68.lr.ph, %for.cond65.preheader
  %icol.2.lcssa = phi i32 [ %icol.0168, %for.cond65.preheader ], [ 0, %for.body68.lr.ph ]
  %exitcond183.not = icmp eq i64 0, 0
  br i1 %exitcond183.not, label %for.body, label %for.cond65.preheader
}

; uselistorder directives
uselistorder ptr null, { 1, 2, 0 }
