; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; REQUIRES: asserts
; RUN: opt -S -enable-loop-to-single-exit -passes=loop-simplifycfg -verify-memoryssa -verify-loop-info -verify-dom-info -verify-loop-lcssa < %s | FileCheck %s

; Test the case where the exit condition can be sunk into the new latch.
define float @foo(i64 %N, ptr noalias %A.ptr, ptr %B.ptr) {
; CHECK-LABEL: define float @foo(
; CHECK-SAME: i64 [[N:%.*]], ptr noalias [[A_PTR:%.*]], ptr [[B_PTR:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_LATCH_SPLIT:%.*]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi float [ 0.000000e+00, [[ENTRY]] ], [ [[SUM_LATCH:%.*]], [[LOOP_LATCH_SPLIT]] ]
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A_PTR]], i64 [[I]]
; CHECK-NEXT:    [[A:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    [[EXITEARLY:%.*]] = fcmp olt float [[A]], 0.000000e+00
; CHECK-NEXT:    br i1 [[EXITEARLY]], label [[LOOP_LATCH_SPLIT]], label [[LOOP_LATCH:%.*]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[SUM_NEXT:%.*]] = fadd fast float [[SUM]], [[A]]
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B_PTR]], i64 [[I]]
; CHECK-NEXT:    store float [[SUM_NEXT]], ptr [[B_ADDR]], align 4
; CHECK-NEXT:    br label [[LOOP_LATCH_SPLIT]]
; CHECK:       loop.latch.split:
; CHECK-NEXT:    [[SUM_LATCH]] = phi float [ [[SUM_NEXT]], [[LOOP_LATCH]] ], [ [[SUM]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    [[TMP0:%.*]] = or i1 [[EXITEARLY]], [[CMP]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[EXIT:%.*]], label [[LOOP_HEADER]]
; CHECK:       exit:
; CHECK-NEXT:    [[SUM_OUT:%.*]] = phi float [ [[SUM_LATCH]], [[LOOP_LATCH_SPLIT]] ]
; CHECK-NEXT:    ret float [[SUM_OUT]]
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %sum = phi float [ 0x0, %entry ], [ %sum.next, %loop.latch ]
  %a.addr = getelementptr inbounds float, ptr %A.ptr, i64 %i
  %a = load float, ptr %a.addr, align 4
  %exitearly = fcmp olt float %a, 0x0
  br i1 %exitearly, label %exit, label %loop.latch

loop.latch:
  %sum.next = fadd fast float %sum, %a
  %b.addr = getelementptr inbounds float, ptr %B.ptr, i64 %i
  store float %sum.next, ptr %b.addr
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  %sum.out = phi float [ %sum, %loop.header ], [ %sum.next, %loop.latch ]
  ret float %sum.out
}

; Test the case where the exit condition can be sunk into the new latch,
; but with some conditions flipped.
define float @foo_flipped(i64 %N, ptr noalias %A.ptr, ptr %B.ptr) {
; CHECK-LABEL: define float @foo_flipped(
; CHECK-SAME: i64 [[N:%.*]], ptr noalias [[A_PTR:%.*]], ptr [[B_PTR:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_NEXT:%.*]], [[LOOP_LATCH_SPLIT:%.*]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi float [ 0.000000e+00, [[ENTRY]] ], [ [[SUM_LATCH:%.*]], [[LOOP_LATCH_SPLIT]] ]
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A_PTR]], i64 [[I]]
; CHECK-NEXT:    [[A:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    [[GOON:%.*]] = fcmp olt float [[A]], 0.000000e+00
; CHECK-NEXT:    br i1 [[GOON]], label [[LOOP_LATCH:%.*]], label [[LOOP_LATCH_SPLIT]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[SUM_NEXT:%.*]] = fadd fast float [[SUM]], [[A]]
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B_PTR]], i64 [[I]]
; CHECK-NEXT:    store float [[SUM_NEXT]], ptr [[B_ADDR]], align 4
; CHECK-NEXT:    br label [[LOOP_LATCH_SPLIT]]
; CHECK:       loop.latch.split:
; CHECK-NEXT:    [[SUM_LATCH]] = phi float [ [[SUM_NEXT]], [[LOOP_LATCH]] ], [ [[SUM]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = xor i1 [[GOON]], true
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    [[TMP1:%.*]] = or i1 [[TMP0]], [[CMP]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[EXIT:%.*]], label [[LOOP_HEADER]]
; CHECK:       exit:
; CHECK-NEXT:    [[SUM_OUT:%.*]] = phi float [ [[SUM_LATCH]], [[LOOP_LATCH_SPLIT]] ]
; CHECK-NEXT:    ret float [[SUM_OUT]]
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %sum = phi float [ 0x0, %entry ], [ %sum.next, %loop.latch ]
  %a.addr = getelementptr inbounds float, ptr %A.ptr, i64 %i
  %a = load float, ptr %a.addr, align 4
  %goon = fcmp olt float %a, 0x0
  br i1 %goon, label %loop.latch, label %exit

loop.latch:
  %sum.next = fadd fast float %sum, %a
  %b.addr = getelementptr inbounds float, ptr %B.ptr, i64 %i
  store float %sum.next, ptr %b.addr
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  %sum.out = phi float [ %sum, %loop.header ], [ %sum.next, %loop.latch ]
  ret float %sum.out
}

; Test more than one early exit as well as a exit condition that cannot be sunk.
define float @bar(i64 %N, ptr noalias %A.ptr, ptr %B.ptr) {
; CHECK-LABEL: define float @bar(
; CHECK-SAME: i64 [[N:%.*]], ptr noalias [[A_PTR:%.*]], ptr [[B_PTR:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[I_LATCH:%.*]], [[LOOP_LATCH_SPLIT:%.*]] ]
; CHECK-NEXT:    [[SUM:%.*]] = phi float [ 0.000000e+00, [[ENTRY]] ], [ [[SUM_LATCH:%.*]], [[LOOP_LATCH_SPLIT]] ]
; CHECK-NEXT:    [[A_ADDR:%.*]] = getelementptr inbounds float, ptr [[A_PTR]], i64 [[I]]
; CHECK-NEXT:    [[A:%.*]] = load float, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    [[EXITEARLY_FIRST:%.*]] = fcmp olt float [[A]], 0.000000e+00
; CHECK-NEXT:    br i1 [[EXITEARLY_FIRST]], label [[LOOP_LATCH_SPLIT]], label [[LOOP_MIDDLE:%.*]]
; CHECK:       loop.middle:
; CHECK-NEXT:    [[SUM_NEXT:%.*]] = fadd fast float [[SUM]], [[A]]
; CHECK-NEXT:    [[B_ADDR:%.*]] = getelementptr inbounds float, ptr [[B_PTR]], i64 [[I]]
; CHECK-NEXT:    store float [[SUM_NEXT]], ptr [[B_ADDR]], align 4
; CHECK-NEXT:    [[EXITEARLY_SECOND:%.*]] = fcmp olt float [[SUM_NEXT]], [[A]]
; CHECK-NEXT:    br i1 [[EXITEARLY_SECOND]], label [[LOOP_LATCH_SPLIT]], label [[LOOP_LATCH:%.*]]
; CHECK:       loop.latch:
; CHECK-NEXT:    [[I_NEXT:%.*]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[CMP:%.*]] = call i1 @baz(i64 [[I_NEXT]], i64 [[N]])
; CHECK-NEXT:    br label [[LOOP_LATCH_SPLIT]]
; CHECK:       loop.latch.split:
; CHECK-NEXT:    [[EARLYEXITCOND:%.*]] = phi i1 [ true, [[LOOP_HEADER]] ], [ true, [[LOOP_MIDDLE]] ], [ [[CMP]], [[LOOP_LATCH]] ]
; CHECK-NEXT:    [[I_LATCH]] = phi i64 [ [[I_NEXT]], [[LOOP_LATCH]] ], [ undef, [[LOOP_HEADER]] ], [ undef, [[LOOP_MIDDLE]] ]
; CHECK-NEXT:    [[SUM_LATCH]] = phi float [ [[SUM_NEXT]], [[LOOP_LATCH]] ], [ [[SUM]], [[LOOP_HEADER]] ], [ [[A]], [[LOOP_MIDDLE]] ]
; CHECK-NEXT:    br i1 [[EARLYEXITCOND]], label [[EXIT:%.*]], label [[LOOP_HEADER]]
; CHECK:       exit:
; CHECK-NEXT:    [[SUM_OUT:%.*]] = phi float [ [[SUM_LATCH]], [[LOOP_LATCH_SPLIT]] ]
; CHECK-NEXT:    ret float [[SUM_OUT]]
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %sum = phi float [ 0x0, %entry ], [ %sum.next, %loop.latch ]
  %a.addr = getelementptr inbounds float, ptr %A.ptr, i64 %i
  %a = load float, ptr %a.addr, align 4
  %exitearly.first = fcmp olt float %a, 0x0
  br i1 %exitearly.first, label %exit, label %loop.middle

loop.middle:
  %sum.next = fadd fast float %sum, %a
  %b.addr = getelementptr inbounds float, ptr %B.ptr, i64 %i
  store float %sum.next, ptr %b.addr
  %exitearly.second = fcmp olt float %sum.next, %a
  br i1 %exitearly.second, label %exit, label %loop.latch

loop.latch:
  %i.next = add nuw i64 %i, 1
  %cmp = call i1 @baz(i64 %i.next, i64 %N)
  br i1 %cmp, label %exit, label %loop.header

exit:
  %sum.out = phi float [ %sum, %loop.header ], [ %a, %loop.middle ], [ %sum.next, %loop.latch ]
  ret float %sum.out
}

declare i1 @baz(i64, i64)
