; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64"

define <vscale x 2 x float> @foo2(float %a, float %b) #0 {
; CHECK-LABEL: foo2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    mov z1.s, s1
; CHECK-NEXT:    punpklo p0.h, p0.b
; CHECK-NEXT:    mov z1.s, p0/m, s0
; CHECK-NEXT:    mov z0.d, z1.d
; CHECK-NEXT:    ret
  %a.insert = insertelement <vscale x 1 x float> poison, float %a, i64 0
  %a.splat = shufflevector <vscale x 1 x float> %a.insert, <vscale x 1 x float> poison, <vscale x 1 x i32> zeroinitializer
  %b.insert = insertelement <vscale x 1 x float> poison, float %b, i64 0
  %b.splat = shufflevector <vscale x 1 x float> %b.insert, <vscale x 1 x float> poison, <vscale x 1 x i32> zeroinitializer
  %res = call <vscale x 2 x float> @llvm.vector.interleave2.nxv2f32(<vscale x 1 x float> %a.splat, <vscale x 1 x float> %b.splat)
  ret <vscale x 2 x float> %res
}

define <vscale x 4 x float> @foo4(float %a, float %b) #0 {
; CHECK-LABEL: foo4:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    mov z1.s, s1
; CHECK-NEXT:    mov z1.s, p0/m, s0
; CHECK-NEXT:    mov z0.d, z1.d
; CHECK-NEXT:    ret
  %a.insert = insertelement <vscale x 2 x float> poison, float %a, i64 0
  %a.splat = shufflevector <vscale x 2 x float> %a.insert, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %b.insert = insertelement <vscale x 2 x float> poison, float %b, i64 0
  %b.splat = shufflevector <vscale x 2 x float> %b.insert, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %res = call <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float> %a.splat, <vscale x 2 x float> %b.splat)
  ret <vscale x 4 x float> %res
}

define <vscale x 8 x float> @fo8(float %a, float %b) #0 {
; CHECK-LABEL: fo8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-NEXT:    mov z2.s, s0
; CHECK-NEXT:    mov z1.s, s1
; CHECK-NEXT:    zip1 z0.s, z2.s, z1.s
; CHECK-NEXT:    zip2 z1.s, z2.s, z1.s
; CHECK-NEXT:    ret
  %a.insert = insertelement <vscale x 4 x float> poison, float %a, i64 0
  %a.splat = shufflevector <vscale x 4 x float> %a.insert, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %b.insert = insertelement <vscale x 4 x float> poison, float %b, i64 0
  %b.splat = shufflevector <vscale x 4 x float> %b.insert, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %res = call <vscale x 8 x float> @llvm.vector.interleave2.nxv8f32(<vscale x 4 x float> %a.splat, <vscale x 4 x float> %b.splat)
  ret <vscale x 8 x float> %res
}

declare <vscale x 2 x float> @llvm.vector.interleave2.nxv2f32(<vscale x 1 x float>, <vscale x 1 x float>)
declare <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float>, <vscale x 2 x float>)
declare <vscale x 8 x float> @llvm.vector.interleave2.nxv8f32(<vscale x 4 x float>, <vscale x 4 x float>)

attributes #0 = { vscale_range(1,16) "target-features"="+sve" }
