; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64"

define <vscale x 4 x float> @foo(float %a, float %b, float %c, float %d) local_unnamed_addr #0 {
; CHECK-LABEL: foo:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $s3 killed $s3 def $z3
; CHECK-NEXT:    // kill: def $s2 killed $s2 def $z2
; CHECK-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-NEXT:    insr z3.s, s3
; CHECK-NEXT:    insr z3.s, s2
; CHECK-NEXT:    insr z3.s, s1
; CHECK-NEXT:    insr z3.s, s0
; CHECK-NEXT:    mov z0.d, z3.d
; CHECK-NEXT:    ret
    %res_a = insertelement <vscale x 4 x float> poison, float %a, i32 0
    %res_b = insertelement <vscale x 4 x float> %res_a, float %b, i32 1
    %res_c = insertelement <vscale x 4 x float> %res_b, float %c, i32 2
    %res_d = insertelement <vscale x 4 x float> %res_c, float %d, i32 3
    ret <vscale x 4 x float> %res_d
}

define <vscale x 4 x float> @with_holes(float %a, float %b, float %c, float %d) local_unnamed_addr #0 {
; CHECK-LABEL: with_holes:
; CHECK:       // %bb.0:
; CHECK-NEXT:    // kill: def $s3 killed $s3 def $z3
; CHECK-NEXT:    // kill: def $s2 killed $s2 def $z2
; CHECK-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-NEXT:    insr z3.s, s3
; CHECK-NEXT:    insr z3.s, s0
; CHECK-NEXT:    insr z3.s, s2
; CHECK-NEXT:    insr z3.s, s0
; CHECK-NEXT:    insr z3.s, s1
; CHECK-NEXT:    insr z3.s, s0
; CHECK-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-NEXT:    insr z3.s, s0
; CHECK-NEXT:    mov z0.d, z3.d
; CHECK-NEXT:    ret
    %res_a = insertelement <vscale x 4 x float> poison, float %a, i32 0
    %res_b = insertelement <vscale x 4 x float> %res_a, float %b, i32 2
    %res_c = insertelement <vscale x 4 x float> %res_b, float %c, i32 4
    %res_d = insertelement <vscale x 4 x float> %res_c, float %d, i32 6
    ret <vscale x 4 x float> %res_d
}

attributes #0 = { vscale_range(1,16) "target-features"="+sve" }
