; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O2 < %s | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

define void @bar(ptr %src, ptr %dst, float %exp) #0 {
; CHECK-LABEL: bar:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str d10, [sp, #-48]! // 8-byte Folded Spill
; CHECK-NEXT:    stp d9, d8, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    fmov s8, s0
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    stp x30, x19, [sp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    mov x19, x1
; CHECK-NEXT:    mov z1.s, z0.s[1]
; CHECK-NEXT:    // kill: def $s0 killed $s0 killed $z0
; CHECK-NEXT:    fmov s9, s1
; CHECK-NEXT:    fmov s1, s8
; CHECK-NEXT:    bl foo
; CHECK-NEXT:    fmov s10, s0
; CHECK-NEXT:    fmov s0, s9
; CHECK-NEXT:    fmov s1, s8
; CHECK-NEXT:    bl foo
; CHECK-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-NEXT:    fmov s1, s10
; CHECK-NEXT:    ldp d9, d8, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    insr z0.s, s0
; CHECK-NEXT:    insr z0.s, s1
; CHECK-NEXT:    str z0, [x19]
; CHECK-NEXT:    ldp x30, x19, [sp, #32] // 16-byte Folded Reload
; CHECK-NEXT:    ldr d10, [sp], #48 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %a = load <vscale x 4 x float>, ptr %src, align 4
  %a_0 = extractelement <vscale x 4 x float> %a, i64 0
  %a_1 = extractelement <vscale x 4 x float> %a, i64 1
  %pow_0 = tail call float @foo(float %a_0, float %exp)
  %pow_1 = tail call float @foo(float %a_1, float %exp)
  %res_0 = insertelement <vscale x 4 x float> poison, float %pow_0, i64 0
  %res_1 = insertelement <vscale x 4 x float> %res_0, float %pow_1, i64 1
  store <vscale x 4 x float> %res_1, ptr %dst, align 4
  ret void
}

define void @use_of_sve_reg_after_call(ptr %src, ptr %dst, float %exp) #0 {
; CHECK-LABEL: use_of_sve_reg_after_call:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x29, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x30, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    addvl sp, sp, #-1
; CHECK-NEXT:    fmov s1, s0
; CHECK-NEXT:    ldr z0, [x0]
; CHECK-NEXT:    mov x19, x1
; CHECK-NEXT:    str z0, [sp] // 16-byte Folded Spill
; CHECK-NEXT:    // kill: def $s0 killed $s0 killed $z0
; CHECK-NEXT:    bl foo
; CHECK-NEXT:    ldr z1, [sp] // 16-byte Folded Reload
; CHECK-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-NEXT:    mov z1.s, z1.s[1]
; CHECK-NEXT:    insr z1.s, s1
; CHECK-NEXT:    insr z1.s, s0
; CHECK-NEXT:    str z1, [x19]
; CHECK-NEXT:    addvl sp, sp, #1
; CHECK-NEXT:    ldp x30, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldr x29, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %a = load <vscale x 4 x float>, ptr %src, align 4
  %a_0 = extractelement <vscale x 4 x float> %a, i64 0
  %pow_0 = tail call float @foo(float %a_0, float %exp)
  %res_0 = insertelement <vscale x 4 x float> poison, float %pow_0, i64 0
  %a_1 = extractelement <vscale x 4 x float> %a, i64 1
  %res_1 = insertelement <vscale x 4 x float> %res_0, float %a_1, i64 1
  store <vscale x 4 x float> %res_1, ptr %dst, align 4
  ret void
}

declare float @foo(float, float) #1

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) vscale_range(2,2) "target-features"="+sve" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
