; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine  -S | FileCheck %s

define <vscale x 4 x float> @zeroinit() {
; CHECK-LABEL: define <vscale x 4 x float> @zeroinit() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <vscale x 4 x float> zeroinitializer
;
entry:
  %0 = call <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float> zeroinitializer, <vscale x 2 x float> zeroinitializer)
  ret <vscale x 4 x float> %0
}

define <vscale x 4 x float> @scalable_splat(float %0) {
; CHECK-LABEL: define <vscale x 4 x float> @scalable_splat(
; CHECK-SAME: float [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x float> poison, float [[TMP0]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x float> [[DOTSPLATINSERT]], <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    ret <vscale x 4 x float> [[DOTSPLAT]]
;
entry:
  %insert = insertelement <vscale x 2 x float> poison, float %0, i64 0
  %shuffle = shufflevector <vscale x 2 x float> %insert, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %res = call <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float> %shuffle, <vscale x 2 x float> %shuffle)
  ret <vscale x 4 x float> %res
}

define <8 x i32> @fixed_constlit() {
; CHECK-LABEL: define <8 x i32> @fixed_constlit() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <8 x i32> splat (i32 42)
;
entry:
  %0 = call <8 x i32> @llvm.vector.interleave2.v8i32(<4 x i32> splat (i32 42), <4 x i32> splat (i32 42))
  ret <8 x i32> %0
}

declare <8 x i32> @llvm.vector.interleave2.v8i32(<4 x i32>, <4 x i32>)
declare <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float>, <vscale x 2 x float>)
