; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=correlated-propagation -S | FileCheck %s

declare void @whatever(i1 %val)

define void @foo(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_LT_1:%.*]] = icmp slt i32 [[A]], 1
; CHECK-NEXT:    br i1 [[A_LT_1]], label %[[EXIT:.*]], label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    call void @whatever(i1 false)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[PREHEADER]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I_NEXT]] = add i32 [[I]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[I_NEXT]], 10
; CHECK-NEXT:    br i1 [[DONE]], label %[[LOOP_EXIT:.*]], label %[[LOOP]]
; CHECK:       [[LOOP_EXIT]]:
; CHECK-NEXT:    call void @whatever(i1 false)
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a.lt.1 = icmp slt i32 %a, 1
  br i1 %a.lt.1, label %exit, label %preheader

preheader:
  %a.is.zero = icmp eq i32 %a, 0
  call void @whatever(i1 %a.is.zero)
  br label %loop

loop:
  %i = phi i32 [ 0, %preheader ], [ %i.next, %loop ]
  %i.next = add i32 %i, 1
  %done = icmp eq i32 %i.next, 10
  br i1 %done, label %loop.exit, label %loop

loop.exit:
  %second.a.is.zero = icmp eq i32 %a, 0
  call void @whatever(i1 %second.a.is.zero)
  br label %exit

exit:
  ret void
}
