; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -disable-output -passes='print<access-info>' %s 2>&1 | FileCheck %s

target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"

; The inner two loops of a naive matrix multiplication.
; %A has the noalias attribute, so vectorization should e legal.
define void @noalias(i64 %N, i64 %M, ptr noalias %A, ptr %B, ptr %C) {
; CHECK-LABEL: 'noalias'
; CHECK-NEXT:    inner.loop:
; CHECK-NEXT:      Memory dependences are safe
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
; CHECK-NEXT:    loop.header:
; CHECK-NEXT:      Memory dependences are safe
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ %i.next, %loop.latch ], [ 0, %entry ]
  %M.is.zero = icmp eq i64 %M, 0
  br i1 %M.is.zero, label %loop.latch, label %inner.loop

inner.loop:
  %j = phi i64 [ %j.next, %inner.loop ], [ 0, %loop.header ]
  %a = phi float [ %a.next, %inner.loop ], [ 0.0, %loop.header ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %j
  %b = load float, ptr %b.addr, align 4
  %jxM = mul i64 %j, %M
  %jxMpi = add i64 %jxM, %i
  %c.addr = getelementptr inbounds float, ptr %C, i64 %jxMpi
  %c = load float, ptr %c.addr, align 4
  %mul = fmul float %b, %c
  %a.next = fadd float %a, %mul
  %j.next = add nuw nsw i64 %j, 1
  %inner.exitcond = icmp eq i64 %j.next, %M
  br i1 %inner.exitcond, label %loop.latch, label %inner.loop

loop.latch:
  %a.lcssa = phi float [ 0x0, %loop.header ], [ %a.next, %inner.loop ]
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  store float %a.lcssa, ptr %a.addr, align 4
  %i.next = add nuw nsw i64 %i, 1
  %loop.exitcond = icmp eq i64 %i.next, %N
  br i1 %loop.exitcond, label %exit, label %loop.header

exit:
  ret void
}

; The inner two loops of a naive matrix multiplication.
; Vectorization is only legal if %A and %B or %C do not alias,
; a runtime-pointer check will be needed.
define void @mayalias(i64 %N, i64 %M, ptr %A, ptr %B, ptr %C) {
; CHECK-LABEL: 'mayalias'
; CHECK-NEXT:    inner.loop:
; CHECK-NEXT:      Memory dependences are safe
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
; CHECK-NEXT:    loop.header:
; CHECK-NEXT:      Memory dependences are safe with run-time checks
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Check 0:
; CHECK-NEXT:        Comparing group ([[GRP1:0x[0-9a-f]+]]):
; CHECK-NEXT:          %a.addr = getelementptr inbounds float, ptr %A, i64 %i
; CHECK-NEXT:        Against group ([[GRP2:0x[0-9a-f]+]]):
; CHECK-NEXT:          %b.addr = getelementptr inbounds float, ptr %B, i64 %j
; CHECK-NEXT:      Check 1:
; CHECK-NEXT:        Comparing group ([[GRP1]]):
; CHECK-NEXT:          %a.addr = getelementptr inbounds float, ptr %A, i64 %i
; CHECK-NEXT:        Against group ([[GRP3:0x[0-9a-f]+]]):
; CHECK-NEXT:          %c.addr = getelementptr inbounds float, ptr %C, i64 %jxMpi
; CHECK-NEXT:      Grouped accesses:
; CHECK-NEXT:        Group [[GRP1]]:
; CHECK-NEXT:          (Low: %A High: ((4 * %N) + %A))
; CHECK-NEXT:            Member: {%A,+,4}<%loop.header>
; CHECK-NEXT:        Group [[GRP2]]:
; CHECK-NEXT:          (Low: %B High: ((4 * %M) + %B))
; CHECK-NEXT:            Member: {%B,+,4}<nuw><%inner.loop>
; CHECK-NEXT:        Group [[GRP3]]:
; CHECK-NEXT:          (Low: (((4 * (-1 + %M) * %M) + %C) umin %C) High: (4 + (4 * (-1 + %M) * %M) + ((-4 + (4 * %N) + %C) umax (-4 + (4 * %N) + (4 * (-1 + %M) * %M) + %C))))
; CHECK-NEXT:            Member: {{\{\{}}%C,+,4}<%loop.header>,+,(4 * %M)}<%inner.loop>
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ %i.next, %loop.latch ], [ 0, %entry ]
  %M.is.zero = icmp eq i64 %M, 0
  br i1 %M.is.zero, label %loop.latch, label %inner.loop

inner.loop:
  %j = phi i64 [ %j.next, %inner.loop ], [ 0, %loop.header ]
  %a = phi float [ %a.next, %inner.loop ], [ 0.0, %loop.header ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %j
  %b = load float, ptr %b.addr, align 4
  %jxM = mul i64 %j, %M
  %jxMpi = add i64 %jxM, %i
  %c.addr = getelementptr inbounds float, ptr %C, i64 %jxMpi
  %c = load float, ptr %c.addr, align 4
  %mul = fmul float %b, %c
  %a.next = fadd float %a, %mul
  %j.next = add nuw nsw i64 %j, 1
  %inner.exitcond = icmp eq i64 %j.next, %M
  br i1 %inner.exitcond, label %loop.latch, label %inner.loop

loop.latch:
  %a.lcssa = phi float [ 0x0, %loop.header ], [ %a.next, %inner.loop ]
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  store float %a.lcssa, ptr %a.addr, align 4
  %i.next = add nuw nsw i64 %i, 1
  %loop.exitcond = icmp eq i64 %i.next, %N
  br i1 %loop.exitcond, label %exit, label %loop.header

exit:
  ret void
}

; Unvectorizeable because of a outer-loop carried dependency.
define void @outer_loop_carried_dep(i64 %N, i64 %M, ptr %A) {
; CHECK-LABEL: 'outer_loop_carried_dep'
; CHECK-NEXT:    inner.loop:
; CHECK-NEXT:      Memory dependences are safe
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
; CHECK-NEXT:    loop.header:
; CHECK-NEXT:      Report: unsafe dependent memory operations in loop.
; CHECK-NEXT:  Backward loop carried data dependence.
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:        Backward:
; CHECK-NEXT:            %load = load i64, ptr %gep.0, align 8 ->
; CHECK-NEXT:            store i64 %sum, ptr %gep.1, align 8
; CHECK-EMPTY:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ %i.next, %loop.latch ], [ 0, %entry ]
  %i.minus.one = sub i64 %i, 1
  %gep.0 = getelementptr inbounds i64, ptr %A, i64 %i.minus.one
  %load = load i64, ptr %gep.0, align 8
  br label %inner.loop

inner.loop:
  %j = phi i64 [ %j.next, %inner.loop ], [ 0, %loop.header ]
  %sum.phi = phi i64 [ %sum, %inner.loop ], [ %load, %loop.header ]
  %sum = add i64 %sum.phi, %j
  %j.next = add nuw nsw i64 %j, 1
  %inner.exitcond = icmp eq i64 %j.next, %M
  br i1 %inner.exitcond, label %loop.latch, label %inner.loop

loop.latch:
  %gep.1 = getelementptr inbounds i64, ptr %A, i64 %i
  store i64 %sum, ptr %gep.1, align 8
  %i.next = add nuw nsw i64 %i, 1
  %loop.exitcond = icmp eq i64 %i.next, %N
  br i1 %loop.exitcond, label %exit, label %loop.header

exit:
  ret void
}

; Unvectorizeable because of a dependency between accesses in the inner and outer loop.
define void @outer_inner_dep(i64 %N, i64 %M, ptr %A) {
; CHECK-LABEL: 'outer_inner_dep'
; CHECK-NEXT:    inner.loop:
; CHECK-NEXT:      Memory dependences are safe
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
; CHECK-NEXT:    loop.header:
; CHECK-NEXT:      Report: unsafe dependent memory operations in loop.
; CHECK-NEXT:  Unknown data dependence.
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:        Unknown:
; CHECK-NEXT:            %load = load i64, ptr %gep.0, align 8 ->
; CHECK-NEXT:            store i64 %sum, ptr %gep.1, align 8
; CHECK-EMPTY:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Grouped accesses:
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
;
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ %i.next, %loop.latch ], [ 0, %entry ]
  br label %inner.loop

inner.loop:
  %j = phi i64 [ %j.next, %inner.loop ], [ 0, %loop.header ]
  %sum.phi = phi i64 [ %sum, %inner.loop ], [ 0, %loop.header ]
  %gep.0 = getelementptr inbounds i64, ptr %A, i64 %j
  %load = load i64, ptr %gep.0, align 8
  %sum = add i64 %sum.phi, %load
  %j.next = add nuw nsw i64 %j, 1
  %inner.exitcond = icmp eq i64 %j.next, %M
  br i1 %inner.exitcond, label %loop.latch, label %inner.loop

loop.latch:
  %gep.1 = getelementptr inbounds i64, ptr %A, i64 %i
  store i64 %sum, ptr %gep.1, align 8
  %i.next = add nuw nsw i64 %i, 1
  %loop.exitcond = icmp eq i64 %i.next, %N
  br i1 %loop.exitcond, label %exit, label %loop.header

exit:
  ret void
}

; A triple-loop nest, somewhat like:
;   for (size_t i = 0; i < N; i++)
;     for (size_t j = 0; j < M; j++)
;       for (size_t k = 0; k < L; k++)
;         A[i][j][k] += B[k][j][i];
define void @quuz(i64 %N, i64 %M, i64 %L, ptr %A, ptr %B) {
; CHECK-LABEL: 'quuz'
; CHECK-NEXT:    inner.loop:
; CHECK-NEXT:      Memory dependences are safe with run-time checks
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Check 0:
; CHECK-NEXT:        Comparing group ([[GRP4:0x[0-9a-f]+]]):
; CHECK-NEXT:          %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
; CHECK-NEXT:          %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
; CHECK-NEXT:        Against group ([[GRP5:0x[0-9a-f]+]]):
; CHECK-NEXT:          %b.gep = getelementptr float, ptr %B, i64 %k.x.M.p.j.x.L.p.i
; CHECK-NEXT:      Grouped accesses:
; CHECK-NEXT:        Group [[GRP4]]:
; CHECK-NEXT:          (Low: {{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop> High: {{\{\{}}((4 * %L) + %A),+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>)
; CHECK-NEXT:            Member: {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop>
; CHECK-NEXT:            Member: {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop>
; CHECK-NEXT:        Group [[GRP5]]:
; CHECK-NEXT:          (Low: ({(((4 + (4 * %M * %L)) * (-1 + %L)) + %B),+,(4 * %L)}<%middle.loop> umin {%B,+,(4 * %L)}<%middle.loop>) High: (4 + ({(((4 + (4 * %M * %L)) * (-1 + %L)) + %B),+,(4 * %L)}<%middle.loop> umax {%B,+,(4 * %L)}<%middle.loop>)))
; CHECK-NEXT:            Member: {{\{\{}}%B,+,(4 * %L)}<%middle.loop>,+,(4 + (4 * %M * %L))}<%inner.loop>
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-NEXT:      {{\{\{}}%B,+,(4 * %L)}<%middle.loop>,+,(4 + (4 * %M * %L))}<%inner.loop> Added Flags: <nusw>
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
; CHECK-NEXT:    middle.loop:
; CHECK-NEXT:      Memory dependences are safe with run-time checks
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Check 0:
; CHECK-NEXT:        Comparing group ([[GRP6:0x[0-9a-f]+]]):
; CHECK-NEXT:          %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
; CHECK-NEXT:          %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
; CHECK-NEXT:        Against group ([[GRP7:0x[0-9a-f]+]]):
; CHECK-NEXT:          %b.gep = getelementptr float, ptr %B, i64 %k.x.M.p.j.x.L.p.i
; CHECK-NEXT:      Grouped accesses:
; CHECK-NEXT:        Group [[GRP6]]:
; CHECK-NEXT:          (Low: ({((4 * (-1 + %M) * %L) + %A),+,(4 * %M * %L)}<%outer.loop> umin {%A,+,(4 * %M * %L)}<%outer.loop>) High: ((4 * %M * %L) + ({((4 * (-1 + %M) * %L) + %A),+,(4 * %M * %L)}<%outer.loop> umax {%A,+,(4 * %M * %L)}<%outer.loop>)))
; CHECK-NEXT:            Member: {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop>
; CHECK-NEXT:            Member: {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop>
; CHECK-NEXT:        Group [[GRP7]]:
; CHECK-NEXT:          (Low: ((((4 + (4 * %M * %L)) * (-1 + %L)) + (((4 * (-1 + %M) * %L) + %B) umin %B)) umin ((4 * (-1 + %M) * %L) + %B) umin %B) High: (4 + ((4 + (4 * %M * %L)) * (-1 + %L)) + (((4 * (-1 + %M) * %L) + (((4 * (-1 + %M) * %L) + %B) umax %B)) umax (((4 + (4 * %M * %L)) * (-1 + %L)) + (4 * (-1 + %M) * %L) + (((4 * (-1 + %M) * %L) + %B) umax %B)))))
; CHECK-NEXT:            Member: {{\{\{}}%B,+,(4 * %L)}<%middle.loop>,+,(4 + (4 * %M * %L))}<%inner.loop>
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-NEXT:      {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop> Added Flags: <nusw>
; CHECK-NEXT:      {{\{\{}}%B,+,(4 * %L)}<%middle.loop>,+,(4 + (4 * %M * %L))}<%inner.loop> Added Flags: <nusw>
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
; CHECK-NEXT:    outer.loop:
; CHECK-NEXT:      Memory dependences are safe with run-time checks
; CHECK-NEXT:      Dependences:
; CHECK-NEXT:      Run-time memory checks:
; CHECK-NEXT:      Check 0:
; CHECK-NEXT:        Comparing group ([[GRP8:0x[0-9a-f]+]]):
; CHECK-NEXT:          %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
; CHECK-NEXT:          %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
; CHECK-NEXT:        Against group ([[GRP9:0x[0-9a-f]+]]):
; CHECK-NEXT:          %b.gep = getelementptr float, ptr %B, i64 %k.x.M.p.j.x.L.p.i
; CHECK-NEXT:      Grouped accesses:
; CHECK-NEXT:        Group [[GRP8]]:
; CHECK-NEXT:          (Low: (((4 * (-1 + %M) * %L) + (((4 * (-1 + %N) * %M * %L) + %A) umin %A)) umin ((4 * (-1 + %N) * %M * %L) + %A) umin %A) High: ((4 * %M * %L) + ((((-4 + (4 * %N * %M)) * %L) + (((4 * (-1 + %N) * %M * %L) + %A) umax %A)) umax ((4 * (-1 + %N) * %M * %L) + (((4 * (-1 + %N) * %M * %L) + %A) umax %A)))))
; CHECK-NEXT:            Member: {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop>
; CHECK-NEXT:            Member: {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop>
; CHECK-NEXT:        Group [[GRP9]]:
; CHECK-NEXT:          (Low: ((((4 + (4 * %M * %L)) * (-1 + %L)) + (((4 * (-1 + %M) * %L) + %B) umin %B)) umin ((4 * (-1 + %M) * %L) + %B) umin %B) High: (4 + ((4 + (4 * %M * %L)) * (-1 + %L)) + (((4 * (-1 + %M) * %L) + (((4 * (-1 + %M) * %L) + %B) umax %B)) umax (((4 + (4 * %M * %L)) * (-1 + %L)) + (4 * (-1 + %M) * %L) + (((4 * (-1 + %M) * %L) + %B) umax %B)))))
; CHECK-NEXT:            Member: {{\{\{}}%B,+,(4 * %L)}<%middle.loop>,+,(4 + (4 * %M * %L))}<%inner.loop>
; CHECK-EMPTY:
; CHECK-NEXT:      Non vectorizable stores to invariant address were not found in loop.
; CHECK-NEXT:      SCEV assumptions:
; CHECK-NEXT:      {{\{\{\{}}%A,+,(4 * %M * %L)}<%outer.loop>,+,(4 * %L)}<%middle.loop>,+,4}<%inner.loop> Added Flags: <nusw>
; CHECK-NEXT:      {{\{\{}}%B,+,(4 * %L)}<%middle.loop>,+,(4 + (4 * %M * %L))}<%inner.loop> Added Flags: <nusw>
; CHECK-EMPTY:
; CHECK-NEXT:      Expressions re-written:
;
entry:
  %N.is.zero = icmp eq i64 %N, 0
  br i1 %N.is.zero, label %exit, label %outer.loop

outer.loop:
  %i = phi i64 [ %i.next, %outer.latch ], [ 0, %entry ]
  %i.x.M = mul i64 %i, %M
  %M.is.zero = icmp eq i64 %M, 0
  br i1 %M.is.zero, label %outer.latch, label %middle.loop

middle.loop:
  %j = phi i64 [ %j.next, %middle.latch ], [ 0, %outer.loop ]
  %i.x.M.p.j = add i64 %i.x.M, %j
  %i.x.M.p.j.x.L = mul i64 %i.x.M.p.j, %L
  %L.is.zero = icmp eq i64 %L, 0
  br i1 %L.is.zero, label %middle.latch, label %inner.loop

inner.loop:
  %k = phi i64 [ %k.next, %inner.loop ], [ 0, %middle.loop ]
  %i.x.M.p.j.x.L.p.k = add i64 %i.x.M.p.j.x.L, %k
  %a.gep = getelementptr float, ptr %A, i64 %i.x.M.p.j.x.L.p.k
  %a.load = load float, ptr %a.gep, align 4
  %k.x.M = mul i64 %k, %M
  %k.x.M.p.j = add i64 %k.x.M, %j
  %k.x.M.p.j.x.L = mul i64 %k.x.M.p.j, %L
  %k.x.M.p.j.x.L.p.i = add i64 %k.x.M.p.j.x.L, %k
  %b.gep = getelementptr float, ptr %B, i64 %k.x.M.p.j.x.L.p.i
  %b.load = load float, ptr %b.gep, align 4
  %res = fadd float %a.load, %b.load
  store float %res, ptr %a.gep, align 4
  %k.next = add nuw nsw i64 %k, 1
  %inner.exitcond = icmp eq i64 %k.next, %L
  br i1 %inner.exitcond, label %middle.latch, label %inner.loop

middle.latch:
  %j.next = add nuw nsw i64 %j, 1
  %middle.exitcond = icmp eq i64 %j.next, %M
  br i1 %middle.exitcond, label %outer.latch, label %middle.loop

outer.latch:
  %i.next = add nuw nsw i64 %i, 1
  %outer.exitcond = icmp eq i64 %i.next, %N
  br i1 %outer.exitcond, label %exit, label %outer.loop

exit:
  ret void
}
