; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-fusion -loop-fusion-shared-accesses-only < %s | FileCheck %s

; A test for the kind of loop nest created by these fortran array expression,
; where each statement expands into a loop nest of depth 2:
;
;    subroutine foo(N, M, A, B, C)
;      integer, intent(in) :: N, M
;      real, intent(in) :: A(N,M), B(N,M)
;      real, intent(inout) :: C(N,M)
;      C = A + B
;      C = C * C
;    end subroutine foo

define void @foo_(ptr %x0, ptr %x1, ptr %x2, ptr %x3, ptr %x4) {
; CHECK-LABEL: define void @foo_(
; CHECK-SAME: ptr [[X0:%.*]], ptr [[X1:%.*]], ptr [[X2:%.*]], ptr [[X3:%.*]], ptr [[X4:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X6:%.*]] = load i32, ptr [[X0]], align 4, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[X7:%.*]] = tail call i32 @llvm.smax.i32(i32 [[X6]], i32 0)
; CHECK-NEXT:    [[X8:%.*]] = zext nneg i32 [[X7]] to i64
; CHECK-NEXT:    [[X9:%.*]] = load i32, ptr [[X1]], align 4, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[X10:%.*]] = tail call i32 @llvm.smax.i32(i32 [[X9]], i32 0)
; CHECK-NEXT:    [[OUTER_TRIP_COUNT:%.*]] = zext nneg i32 [[X10]] to i64
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X9]], 1
; CHECK-NEXT:    br i1 [[DOTNOT]], label %[[EXIT:.*]], label %[[LOOP_ONE_OUTER_PREHEADER:.*]]
; CHECK:       [[LOOP_ONE_OUTER_PREHEADER]]:
; CHECK-NEXT:    [[DOTNOT9:%.*]] = icmp slt i32 [[X6]], 1
; CHECK-NEXT:    [[X12:%.*]] = add nuw nsw i64 [[X8]], 2
; CHECK-NEXT:    [[X13:%.*]] = icmp sgt i32 [[X6]], 0
; CHECK-NEXT:    [[DOTNEG:%.*]] = sext i1 [[X13]] to i64
; CHECK-NEXT:    [[INNER_TRIP_COUNT:%.*]] = add nsw i64 [[X12]], [[DOTNEG]]
; CHECK-NEXT:    [[INVARIANT_GEP6:%.*]] = getelementptr i8, ptr [[X4]], i64 -4
; CHECK-NEXT:    br label %[[LOOP_ONE_HEADER:.*]]
; CHECK:       [[LOOP_ONE_HEADER]]:
; CHECK-NEXT:    [[X15:%.*]] = phi i64 [ 1, %[[LOOP_ONE_OUTER_PREHEADER]] ], [ [[X32:%.*]], %[[LOOP_TWO_LATCH:.*]] ]
; CHECK-NEXT:    [[X33:%.*]] = phi i64 [ 1, %[[LOOP_ONE_OUTER_PREHEADER]] ], [ [[X41:%.*]], %[[LOOP_TWO_LATCH]] ]
; CHECK-NEXT:    br i1 [[DOTNOT9]], label %[[LOOP_TWO_LATCH]], label %[[LOOP_ONE_PREHEADER:.*]]
; CHECK:       [[LOOP_ONE_PREHEADER]]:
; CHECK-NEXT:    [[X16:%.*]] = add nsw i64 [[X15]], -1
; CHECK-NEXT:    [[X17:%.*]] = mul nuw nsw i64 [[X16]], [[X8]]
; CHECK-NEXT:    [[X18:%.*]] = add nsw i64 [[X17]], -1
; CHECK-NEXT:    [[X34:%.*]] = add nsw i64 [[X33]], -1
; CHECK-NEXT:    [[X35:%.*]] = mul nuw nsw i64 [[X34]], [[X8]]
; CHECK-NEXT:    [[GEP7:%.*]] = getelementptr float, ptr [[INVARIANT_GEP6]], i64 [[X35]]
; CHECK-NEXT:    br label %[[LOOP_ONE_INNER:.*]]
; CHECK:       [[LOOP_ONE_INNER]]:
; CHECK-NEXT:    [[X23:%.*]] = phi i64 [ 1, %[[LOOP_ONE_PREHEADER]] ], [ [[X31:%.*]], %[[LOOP_ONE_INNER]] ]
; CHECK-NEXT:    [[X37:%.*]] = phi i64 [ 1, %[[LOOP_ONE_PREHEADER]] ], [ [[X40:%.*]], %[[LOOP_ONE_INNER]] ]
; CHECK-NEXT:    [[X24:%.*]] = add nsw i64 [[X18]], [[X23]]
; CHECK-NEXT:    [[X25:%.*]] = getelementptr float, ptr [[X2]], i64 [[X24]]
; CHECK-NEXT:    [[X26:%.*]] = getelementptr float, ptr [[X3]], i64 [[X24]]
; CHECK-NEXT:    [[X27:%.*]] = load float, ptr [[X25]], align 4, !tbaa [[TBAA8:![0-9]+]]
; CHECK-NEXT:    [[X28:%.*]] = load float, ptr [[X26]], align 4, !tbaa [[TBAA10:![0-9]+]]
; CHECK-NEXT:    [[X29:%.*]] = fadd contract float [[X27]], [[X28]]
; CHECK-NEXT:    [[X30:%.*]] = getelementptr float, ptr [[X4]], i64 [[X24]]
; CHECK-NEXT:    store float [[X29]], ptr [[X30]], align 4, !tbaa [[TBAA12:![0-9]+]]
; CHECK-NEXT:    [[X31]] = add nuw nsw i64 [[X23]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[X31]], [[INNER_TRIP_COUNT]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr float, ptr [[GEP7]], i64 [[X37]]
; CHECK-NEXT:    [[X38:%.*]] = load float, ptr [[GEP]], align 4, !tbaa [[TBAA12]]
; CHECK-NEXT:    [[X39:%.*]] = fmul contract float [[X38]], [[X38]]
; CHECK-NEXT:    store float [[X39]], ptr [[GEP]], align 4, !tbaa [[TBAA12]]
; CHECK-NEXT:    [[X40]] = add nuw nsw i64 [[X37]], 1
; CHECK-NEXT:    [[EXITCOND15_NOT:%.*]] = icmp eq i64 [[X40]], [[INNER_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND15_NOT]], label %[[LOOP_TWO_LATCH_LOOPEXIT:.*]], label %[[LOOP_ONE_INNER]]
; CHECK:       [[LOOP_TWO_LATCH_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[LOOP_TWO_LATCH]]
; CHECK:       [[LOOP_TWO_LATCH]]:
; CHECK-NEXT:    [[X32]] = add nuw nsw i64 [[X15]], 1
; CHECK-NEXT:    [[EXITCOND13_NOT:%.*]] = icmp eq i64 [[X32]], [[OUTER_TRIP_COUNT]]
; CHECK-NEXT:    [[X41]] = add nuw nsw i64 [[X33]], 1
; CHECK-NEXT:    [[EXITCOND17_NOT:%.*]] = icmp eq i64 [[X41]], [[OUTER_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND17_NOT]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP_ONE_HEADER]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %x6 = load i32, ptr %x0, align 4, !tbaa !0
  %x7 = tail call i32 @llvm.smax.i32(i32 %x6, i32 0)
  %x8 = zext nneg i32 %x7 to i64
  %x9 = load i32, ptr %x1, align 4, !tbaa !6
  %x10 = tail call i32 @llvm.smax.i32(i32 %x9, i32 0)
  %outer.trip.count = zext nneg i32 %x10 to i64
  %.not = icmp slt i32 %x9, 1
  br i1 %.not, label %exit, label %loop.one.outer.preheader

loop.one.outer.preheader:                         ; preds = %entry
  %.not9 = icmp slt i32 %x6, 1
  %x12 = add nuw nsw i64 %x8, 2
  %x13 = icmp sgt i32 %x6, 0
  %.neg = sext i1 %x13 to i64
  %inner.trip.count = add nsw i64 %x12, %.neg
  br label %loop.one.header

loop.one.header:                                  ; preds = %loop.one.latch, %loop.one.outer.preheader
  %x15 = phi i64 [ 1, %loop.one.outer.preheader ], [ %x32, %loop.one.latch ]
  br i1 %.not9, label %loop.one.latch, label %loop.one.preheader

loop.one.preheader:                               ; preds = %loop.one.header
  %x16 = add nsw i64 %x15, -1
  %x17 = mul nuw nsw i64 %x16, %x8
  %x18 = add nsw i64 %x17, -1
  br label %loop.one.inner

loop.one.inner:                                   ; preds = %loop.one.inner, %loop.one.preheader
  %x23 = phi i64 [ 1, %loop.one.preheader ], [ %x31, %loop.one.inner ]
  %x24 = add nsw i64 %x18, %x23
  %x25 = getelementptr float, ptr %x2, i64 %x24
  %x26 = getelementptr float, ptr %x3, i64 %x24
  %x27 = load float, ptr %x25, align 4, !tbaa !8
  %x28 = load float, ptr %x26, align 4, !tbaa !10
  %x29 = fadd contract float %x27, %x28
  %x30 = getelementptr float, ptr %x4, i64 %x24
  store float %x29, ptr %x30, align 4, !tbaa !12
  %x31 = add nuw nsw i64 %x23, 1
  %exitcond.not = icmp eq i64 %x31, %inner.trip.count
  br i1 %exitcond.not, label %loop.one.latch, label %loop.one.inner

loop.one.latch:                                   ; preds = %loop.one.inner, %loop.one.header
  %x32 = add nuw nsw i64 %x15, 1
  %exitcond13.not = icmp eq i64 %x32, %outer.trip.count
  br i1 %exitcond13.not, label %bridge, label %loop.one.header

bridge:                                           ; preds = %loop.one.latch
  %invariant.gep6 = getelementptr i8, ptr %x4, i64 -4
  br label %loop.two.header

loop.two.header:                                  ; preds = %loop.two.latch, %bridge
  %x33 = phi i64 [ 1, %bridge ], [ %x41, %loop.two.latch ]
  br i1 %.not9, label %loop.two.latch, label %loop.two.preheader

loop.two.preheader:                               ; preds = %loop.two.header
  %x34 = add nsw i64 %x33, -1
  %x35 = mul nuw nsw i64 %x34, %x8
  %gep7 = getelementptr float, ptr %invariant.gep6, i64 %x35
  br label %loop.two.inner

loop.two.inner:                                   ; preds = %loop.two.inner, %loop.two.preheader
  %x37 = phi i64 [ 1, %loop.two.preheader ], [ %x40, %loop.two.inner ]
  %gep = getelementptr float, ptr %gep7, i64 %x37
  %x38 = load float, ptr %gep, align 4, !tbaa !12
  %x39 = fmul contract float %x38, %x38
  store float %x39, ptr %gep, align 4, !tbaa !12
  %x40 = add nuw nsw i64 %x37, 1
  %exitcond15.not = icmp eq i64 %x40, %inner.trip.count
  br i1 %exitcond15.not, label %loop.two.latch, label %loop.two.inner

loop.two.latch:                                   ; preds = %loop.two.inner, %loop.two.header
  %x41 = add nuw nsw i64 %x33, 1
  %exitcond17.not = icmp eq i64 %x41, %outer.trip.count
  br i1 %exitcond17.not, label %exit, label %loop.two.header

exit:                                             ; preds = %loop.two.latch, %entry
  ret void
}

declare i32 @llvm.smax.i32(i32, i32)

!0 = !{!1, !1, i64 0}
!1 = !{!"dummy arg data/_QFfooEn", !2, i64 0}
!2 = !{!"dummy arg data", !3, i64 0}
!3 = !{!"any data access", !4, i64 0}
!4 = !{!"any access", !5, i64 0}
!5 = !{!"Flang function root _QPfoo"}
!6 = !{!7, !7, i64 0}
!7 = !{!"dummy arg data/_QFfooEm", !2, i64 0}
!8 = !{!9, !9, i64 0}
!9 = !{!"dummy arg data/_QFfooEa", !2, i64 0}
!10 = !{!11, !11, i64 0}
!11 = !{!"dummy arg data/_QFfooEb", !2, i64 0}
!12 = !{!13, !13, i64 0}
!13 = !{!"dummy arg data/_QFfooEc", !2, i64 0}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"dummy arg data/_QFfooEn", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"dummy arg data", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"any data access", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"any access", [[META5:![0-9]+]], i64 0}
; CHECK: [[META5]] = !{!"Flang function root _QPfoo"}
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK: [[META7]] = !{!"dummy arg data/_QFfooEm", [[META2]], i64 0}
; CHECK: [[TBAA8]] = !{[[META9:![0-9]+]], [[META9]], i64 0}
; CHECK: [[META9]] = !{!"dummy arg data/_QFfooEa", [[META2]], i64 0}
; CHECK: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
; CHECK: [[META11]] = !{!"dummy arg data/_QFfooEb", [[META2]], i64 0}
; CHECK: [[TBAA12]] = !{[[META13:![0-9]+]], [[META13]], i64 0}
; CHECK: [[META13]] = !{!"dummy arg data/_QFfooEc", [[META2]], i64 0}
;.
