; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=aarch64 -mattr=+sve -passes=loop-vectorize,instcombine,simplifycfg \
; RUN:     -force-vector-interleave=1 -experimental-boscc \
; RUN:     -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue < %s | FileCheck -check-prefix=CHECK-IC1 %s
; RUN: opt -S -mtriple=aarch64 -mattr=+sve -passes=loop-vectorize,instcombine,simplifycfg \
; RUN:     -force-vector-interleave=2 -experimental-boscc \
; RUN:     -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue < %s | FileCheck -check-prefix=CHECK-IC2 %s

define void @test_left_likely(
; CHECK-IC1-LABEL: define void @test_left_likely(
; CHECK-IC1-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-IC1-NEXT:  [[ENTRY:.*]]:
; CHECK-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; CHECK-IC1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP3]])
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC1:       [[VECTOR_BODY]]:
; CHECK-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[IF_TRUE2:.*]] ]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[IF_TRUE2]] ]
; CHECK-IC1-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP5]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[IF_TRUE2]] ]
; CHECK-IC1-NEXT:    [[TMP6:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[TMP7:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC1-NEXT:    [[TMP8:%.*]] = icmp eq <vscale x 4 x i64> [[TMP7]], zeroinitializer
; CHECK-IC1-NEXT:    [[TMP9:%.*]] = xor <vscale x 4 x i1> [[TMP8]], splat (i1 true)
; CHECK-IC1-NEXT:    [[TMP10:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP9]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP11:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP10]])
; CHECK-IC1-NEXT:    br i1 [[TMP11]], label %[[IF_FALSE1:.*]], label %[[IF_TRUE2]]
; CHECK-IC1:       [[IF_FALSE1]]:
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP12:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD]], [[WIDE_MASKED_LOAD]]
; CHECK-IC1-NEXT:    br label %[[IF_TRUE2]]
; CHECK-IC1:       [[IF_TRUE2]]:
; CHECK-IC1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ [[TMP12]], %[[IF_FALSE1]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC1-NEXT:    [[TMP13:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP8]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP14:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP14]], i32 4, <vscale x 4 x i1> [[TMP13]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP15:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD3]], [[WIDE_MASKED_LOAD3]]
; CHECK-IC1-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> [[VEC_PHI]], <vscale x 4 x float> [[TMP15]]
; CHECK-IC1-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP4]])
; CHECK-IC1-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-IC1-NEXT:    [[TMP16:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC1-NEXT:    br i1 [[TMP16]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-IC1:       [[EXIT]]:
; CHECK-IC1-NEXT:    ret void
;
; CHECK-IC2-LABEL: define void @test_left_likely(
; CHECK-IC2-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP3]], 3
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP4]])
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 2
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP7]], i64 [[N]])
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[IF_TRUE5:.*]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[IF_TRUE5]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT10:%.*]], %[[IF_TRUE5]] ]
; CHECK-IC2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP8]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[IF_TRUE5]] ]
; CHECK-IC2-NEXT:    [[STEP_ADD:%.*]] = add <vscale x 4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = urem <vscale x 4 x i64> [[STEP_ADD]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = icmp eq <vscale x 4 x i64> [[TMP10]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP13:%.*]] = icmp eq <vscale x 4 x i64> [[TMP11]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP14:%.*]] = xor <vscale x 4 x i1> [[TMP12]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP15:%.*]] = xor <vscale x 4 x i1> [[TMP13]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP16:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP14]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP17:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP15]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP18:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP16]])
; CHECK-IC2-NEXT:    [[TMP19:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP17]])
; CHECK-IC2-NEXT:    [[TMP20:%.*]] = or i1 [[TMP18]], [[TMP19]]
; CHECK-IC2-NEXT:    br i1 [[TMP20]], label %[[IF_FALSE3:.*]], label %[[IF_TRUE5]]
; CHECK-IC2:       [[IF_FALSE3]]:
; CHECK-IC2-NEXT:    [[TMP21:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX:%.*]] = shl i64 [[TMP21]], 4
; CHECK-IC2-NEXT:    [[TMP22:%.*]] = getelementptr i8, ptr [[TMP9]], i64 [[DOTIDX]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[TMP16]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP22]], i32 4, <vscale x 4 x i1> [[TMP17]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP23:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD]], [[WIDE_MASKED_LOAD]]
; CHECK-IC2-NEXT:    [[TMP24:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD4]], [[WIDE_MASKED_LOAD4]]
; CHECK-IC2-NEXT:    br label %[[IF_TRUE5]]
; CHECK-IC2:       [[IF_TRUE5]]:
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ [[TMP23]], %[[IF_FALSE3]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI6:%.*]] = phi <vscale x 4 x float> [ [[TMP24]], %[[IF_FALSE3]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[TMP25:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP26:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP13]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP27:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP28:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX11:%.*]] = shl i64 [[TMP28]], 4
; CHECK-IC2-NEXT:    [[TMP29:%.*]] = getelementptr i8, ptr [[TMP27]], i64 [[DOTIDX11]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD7:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP27]], i32 4, <vscale x 4 x i1> [[TMP25]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD8:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP29]], i32 4, <vscale x 4 x i1> [[TMP26]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP30:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD7]], [[WIDE_MASKED_LOAD7]]
; CHECK-IC2-NEXT:    [[TMP31:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD8]], [[WIDE_MASKED_LOAD8]]
; CHECK-IC2-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP16]], <vscale x 4 x float> [[VEC_PHI]], <vscale x 4 x float> [[TMP30]]
; CHECK-IC2-NEXT:    [[PREDPHI9:%.*]] = select <vscale x 4 x i1> [[TMP17]], <vscale x 4 x float> [[VEC_PHI6]], <vscale x 4 x float> [[TMP31]]
; CHECK-IC2-NEXT:    [[TMP32:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX12:%.*]] = shl i64 [[TMP32]], 4
; CHECK-IC2-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i8, ptr [[TMP9]], i64 [[DOTIDX12]]
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI9]], ptr [[TMP33]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-IC2-NEXT:    [[TMP34:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP35:%.*]] = shl i64 [[TMP34]], 2
; CHECK-IC2-NEXT:    [[TMP36:%.*]] = add i64 [[INDEX]], [[TMP35]]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT10]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP36]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[STEP_ADD]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP37:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC2-NEXT:    br i1 [[TMP37]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-IC2:       [[EXIT]]:
; CHECK-IC2-NEXT:    ret void
;
  i64 %N, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %mod = urem i64 %i, 123
  %cond = icmp eq i64 %mod, 0
  br i1 %cond, label %if.true, label %if.false, !prof !1

if.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  %add = fadd float %a.val, %a.val
  br label %loop.latch

if.false:
  %b.val = load float, ptr %b.addr, align 4
  %mul = fmul float %b.val, %b.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %add, %if.true ], [ %mul, %if.false ]
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_right_likely(
; CHECK-IC1-LABEL: define void @test_right_likely(
; CHECK-IC1-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0]] {
; CHECK-IC1-NEXT:  [[ENTRY:.*]]:
; CHECK-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; CHECK-IC1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP3]])
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC1:       [[VECTOR_BODY]]:
; CHECK-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH3:.*]] ]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH3]] ]
; CHECK-IC1-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP5]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH3]] ]
; CHECK-IC1-NEXT:    [[TMP6:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[TMP7:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC1-NEXT:    [[TMP8:%.*]] = icmp eq <vscale x 4 x i64> [[TMP7]], zeroinitializer
; CHECK-IC1-NEXT:    [[TMP9:%.*]] = xor <vscale x 4 x i1> [[TMP8]], splat (i1 true)
; CHECK-IC1-NEXT:    [[TMP10:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP9]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP11:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD]], [[WIDE_MASKED_LOAD]]
; CHECK-IC1-NEXT:    [[TMP12:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP8]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP12]])
; CHECK-IC1-NEXT:    br i1 [[TMP13]], label %[[IF_TRUE1:.*]], label %[[LOOP_LATCH3]]
; CHECK-IC1:       [[IF_TRUE1]]:
; CHECK-IC1-NEXT:    [[TMP14:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD2:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP14]], i32 4, <vscale x 4 x i1> [[TMP12]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP15:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD2]], [[WIDE_MASKED_LOAD2]]
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH3]]
; CHECK-IC1:       [[LOOP_LATCH3]]:
; CHECK-IC1-NEXT:    [[TMP17:%.*]] = phi <vscale x 4 x float> [ [[TMP15]], %[[IF_TRUE1]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC1-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> [[TMP11]], <vscale x 4 x float> [[TMP17]]
; CHECK-IC1-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP4]])
; CHECK-IC1-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-IC1-NEXT:    [[TMP16:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC1-NEXT:    br i1 [[TMP16]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK-IC1:       [[EXIT]]:
; CHECK-IC1-NEXT:    ret void
;
; CHECK-IC2-LABEL: define void @test_right_likely(
; CHECK-IC2-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP3]], 3
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP4]])
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 2
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP7]], i64 [[N]])
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH7:.*]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT10:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP8]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC2-NEXT:    [[STEP_ADD:%.*]] = add <vscale x 4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = urem <vscale x 4 x i64> [[STEP_ADD]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = icmp eq <vscale x 4 x i64> [[TMP10]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP13:%.*]] = icmp eq <vscale x 4 x i64> [[TMP11]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP14:%.*]] = xor <vscale x 4 x i1> [[TMP12]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP15:%.*]] = xor <vscale x 4 x i1> [[TMP13]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP16:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP14]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP17:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP15]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP18:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX:%.*]] = shl i64 [[TMP18]], 4
; CHECK-IC2-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[TMP9]], i64 [[DOTIDX]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[TMP16]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP19]], i32 4, <vscale x 4 x i1> [[TMP17]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP20:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD]], [[WIDE_MASKED_LOAD]]
; CHECK-IC2-NEXT:    [[TMP21:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD3]], [[WIDE_MASKED_LOAD3]]
; CHECK-IC2-NEXT:    [[TMP22:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP23:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP13]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP24:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP22]])
; CHECK-IC2-NEXT:    [[TMP25:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP23]])
; CHECK-IC2-NEXT:    [[TMP26:%.*]] = or i1 [[TMP24]], [[TMP25]]
; CHECK-IC2-NEXT:    br i1 [[TMP26]], label %[[IF_TRUE4:.*]], label %[[LOOP_LATCH7]]
; CHECK-IC2:       [[IF_TRUE4]]:
; CHECK-IC2-NEXT:    [[TMP27:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP28:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX11:%.*]] = shl i64 [[TMP28]], 4
; CHECK-IC2-NEXT:    [[TMP29:%.*]] = getelementptr i8, ptr [[TMP27]], i64 [[DOTIDX11]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP27]], i32 4, <vscale x 4 x i1> [[TMP22]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD6:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP29]], i32 4, <vscale x 4 x i1> [[TMP23]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP30:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD5]], [[WIDE_MASKED_LOAD5]]
; CHECK-IC2-NEXT:    [[TMP31:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD6]], [[WIDE_MASKED_LOAD6]]
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH7]]
; CHECK-IC2:       [[LOOP_LATCH7]]:
; CHECK-IC2-NEXT:    [[TMP38:%.*]] = phi <vscale x 4 x float> [ [[TMP30]], %[[IF_TRUE4]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[TMP39:%.*]] = phi <vscale x 4 x float> [ [[TMP31]], %[[IF_TRUE4]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP16]], <vscale x 4 x float> [[TMP20]], <vscale x 4 x float> [[TMP38]]
; CHECK-IC2-NEXT:    [[PREDPHI9:%.*]] = select <vscale x 4 x i1> [[TMP17]], <vscale x 4 x float> [[TMP21]], <vscale x 4 x float> [[TMP39]]
; CHECK-IC2-NEXT:    [[TMP32:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX12:%.*]] = shl i64 [[TMP32]], 4
; CHECK-IC2-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i8, ptr [[TMP9]], i64 [[DOTIDX12]]
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI9]], ptr [[TMP33]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-IC2-NEXT:    [[TMP34:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP35:%.*]] = shl i64 [[TMP34]], 2
; CHECK-IC2-NEXT:    [[TMP36:%.*]] = add i64 [[INDEX]], [[TMP35]]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT10]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP36]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[STEP_ADD]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP37:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC2-NEXT:    br i1 [[TMP37]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK-IC2:       [[EXIT]]:
; CHECK-IC2-NEXT:    ret void
;
  i64 %N, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %mod = urem i64 %i, 123
  %cond = icmp eq i64 %mod, 0
  br i1 %cond, label %if.true, label %if.false, !prof !0

if.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  %add = fadd float %a.val, %a.val
  br label %loop.latch

if.false:
  %b.val = load float, ptr %b.addr, align 4
  %mul = fmul float %b.val, %b.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %add, %if.true ], [ %mul, %if.false ]
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}


define void @test_left_bypass(
; CHECK-IC1-LABEL: define void @test_left_bypass(
; CHECK-IC1-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0]] {
; CHECK-IC1-NEXT:  [[ENTRY:.*]]:
; CHECK-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; CHECK-IC1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP3]])
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC1:       [[VECTOR_BODY]]:
; CHECK-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH3:.*]] ]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH3]] ]
; CHECK-IC1-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP5]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH3]] ]
; CHECK-IC1-NEXT:    [[TMP6:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP7]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP8:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC1-NEXT:    [[TMP9:%.*]] = icmp ne <vscale x 4 x i64> [[TMP8]], zeroinitializer
; CHECK-IC1-NEXT:    [[TMP10:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP9]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP11:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP10]])
; CHECK-IC1-NEXT:    br i1 [[TMP11]], label %[[IF_FALSE1:.*]], label %[[LOOP_LATCH3]]
; CHECK-IC1:       [[IF_FALSE1]]:
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD2:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP12:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD2]], [[WIDE_MASKED_LOAD2]]
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH3]]
; CHECK-IC1:       [[LOOP_LATCH3]]:
; CHECK-IC1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ [[TMP12]], %[[IF_FALSE1]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC1-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> [[VEC_PHI]], <vscale x 4 x float> [[WIDE_MASKED_LOAD]]
; CHECK-IC1-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP4]])
; CHECK-IC1-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-IC1-NEXT:    [[TMP13:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC1-NEXT:    br i1 [[TMP13]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK-IC1:       [[EXIT]]:
; CHECK-IC1-NEXT:    ret void
;
; CHECK-IC2-LABEL: define void @test_left_bypass(
; CHECK-IC2-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP3]], 3
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP4]])
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 2
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP7]], i64 [[N]])
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH7:.*]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT10:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP8]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC2-NEXT:    [[STEP_ADD:%.*]] = add <vscale x 4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX:%.*]] = shl i64 [[TMP11]], 4
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i8, ptr [[TMP10]], i64 [[DOTIDX]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP10]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP12]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP13:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP14:%.*]] = urem <vscale x 4 x i64> [[STEP_ADD]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP15:%.*]] = icmp ne <vscale x 4 x i64> [[TMP13]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP16:%.*]] = icmp ne <vscale x 4 x i64> [[TMP14]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP17:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP15]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP18:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP16]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP19:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP17]])
; CHECK-IC2-NEXT:    [[TMP20:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP18]])
; CHECK-IC2-NEXT:    [[TMP21:%.*]] = or i1 [[TMP19]], [[TMP20]]
; CHECK-IC2-NEXT:    br i1 [[TMP21]], label %[[IF_FALSE4:.*]], label %[[LOOP_LATCH7]]
; CHECK-IC2:       [[IF_FALSE4]]:
; CHECK-IC2-NEXT:    [[TMP22:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX11:%.*]] = shl i64 [[TMP22]], 4
; CHECK-IC2-NEXT:    [[TMP23:%.*]] = getelementptr i8, ptr [[TMP9]], i64 [[DOTIDX11]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[TMP17]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD6:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP23]], i32 4, <vscale x 4 x i1> [[TMP18]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP24:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD5]], [[WIDE_MASKED_LOAD5]]
; CHECK-IC2-NEXT:    [[TMP25:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD6]], [[WIDE_MASKED_LOAD6]]
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH7]]
; CHECK-IC2:       [[LOOP_LATCH7]]:
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ [[TMP24]], %[[IF_FALSE4]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI8:%.*]] = phi <vscale x 4 x float> [ [[TMP25]], %[[IF_FALSE4]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP17]], <vscale x 4 x float> [[VEC_PHI]], <vscale x 4 x float> [[WIDE_MASKED_LOAD]]
; CHECK-IC2-NEXT:    [[PREDPHI9:%.*]] = select <vscale x 4 x i1> [[TMP18]], <vscale x 4 x float> [[VEC_PHI8]], <vscale x 4 x float> [[WIDE_MASKED_LOAD3]]
; CHECK-IC2-NEXT:    [[TMP26:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX12:%.*]] = shl i64 [[TMP26]], 4
; CHECK-IC2-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i8, ptr [[TMP9]], i64 [[DOTIDX12]]
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI9]], ptr [[TMP27]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-IC2-NEXT:    [[TMP28:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP29:%.*]] = shl i64 [[TMP28]], 2
; CHECK-IC2-NEXT:    [[TMP30:%.*]] = add i64 [[INDEX]], [[TMP29]]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT10]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP30]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[STEP_ADD]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP31:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC2-NEXT:    br i1 [[TMP31]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK-IC2:       [[EXIT]]:
; CHECK-IC2-NEXT:    ret void
;
  i64 %N, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  %mod = urem i64 %i, 123
  %cond = icmp eq i64 %mod, 0
  br i1 %cond, label %loop.latch, label %if.false, !prof !1

if.false:
  %b.val = load float, ptr %b.addr, align 4
  %mul = fmul float %b.val, %b.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %a.val, %loop.header ], [ %mul, %if.false ]
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_right_bypass(
; CHECK-IC1-LABEL: define void @test_right_bypass(
; CHECK-IC1-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0]] {
; CHECK-IC1-NEXT:  [[ENTRY:.*]]:
; CHECK-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; CHECK-IC1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP3]])
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC1:       [[VECTOR_BODY]]:
; CHECK-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH2:.*]] ]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH2]] ]
; CHECK-IC1-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP5]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH2]] ]
; CHECK-IC1-NEXT:    [[TMP6:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC1-NEXT:    [[TMP7:%.*]] = icmp eq <vscale x 4 x i64> [[TMP6]], zeroinitializer
; CHECK-IC1-NEXT:    [[TMP8:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP7]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP9:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP8]])
; CHECK-IC1-NEXT:    br i1 [[TMP9]], label %[[IF_TRUE1:.*]], label %[[LOOP_LATCH2]]
; CHECK-IC1:       [[IF_TRUE1]]:
; CHECK-IC1-NEXT:    [[TMP10:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP10]], i32 4, <vscale x 4 x i1> [[TMP8]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP11:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD]], [[WIDE_MASKED_LOAD]]
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH2]]
; CHECK-IC1:       [[LOOP_LATCH2]]:
; CHECK-IC1-NEXT:    [[TMP14:%.*]] = phi <vscale x 4 x float> [ [[TMP11]], %[[IF_TRUE1]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC1-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP8]], <vscale x 4 x float> [[TMP14]], <vscale x 4 x float> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP12]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP4]])
; CHECK-IC1-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-IC1-NEXT:    [[TMP13:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC1-NEXT:    br i1 [[TMP13]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK-IC1:       [[EXIT]]:
; CHECK-IC1-NEXT:    ret void
;
; CHECK-IC2-LABEL: define void @test_right_bypass(
; CHECK-IC2-SAME: i64 [[N:%.*]], ptr [[A:%.*]], ptr noalias [[B:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP3]], 3
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP4]])
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 2
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP7]], i64 [[N]])
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH5:.*]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH5]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT8:%.*]], %[[LOOP_LATCH5]] ]
; CHECK-IC2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP8]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH5]] ]
; CHECK-IC2-NEXT:    [[STEP_ADD:%.*]] = add <vscale x 4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = urem <vscale x 4 x i64> [[STEP_ADD]], splat (i64 123)
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = icmp eq <vscale x 4 x i64> [[TMP9]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = icmp eq <vscale x 4 x i64> [[TMP10]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP13:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP11]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP14:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP15:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP13]])
; CHECK-IC2-NEXT:    [[TMP16:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP14]])
; CHECK-IC2-NEXT:    [[TMP17:%.*]] = or i1 [[TMP15]], [[TMP16]]
; CHECK-IC2-NEXT:    br i1 [[TMP17]], label %[[IF_TRUE3:.*]], label %[[LOOP_LATCH5]]
; CHECK-IC2:       [[IF_TRUE3]]:
; CHECK-IC2-NEXT:    [[TMP18:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP19:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX:%.*]] = shl i64 [[TMP19]], 4
; CHECK-IC2-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[TMP18]], i64 [[DOTIDX]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP18]], i32 4, <vscale x 4 x i1> [[TMP13]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP20]], i32 4, <vscale x 4 x i1> [[TMP14]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP21:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD]], [[WIDE_MASKED_LOAD]]
; CHECK-IC2-NEXT:    [[TMP22:%.*]] = fadd <vscale x 4 x float> [[WIDE_MASKED_LOAD4]], [[WIDE_MASKED_LOAD4]]
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH5]]
; CHECK-IC2:       [[LOOP_LATCH5]]:
; CHECK-IC2-NEXT:    [[TMP30:%.*]] = phi <vscale x 4 x float> [ [[TMP21]], %[[IF_TRUE3]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[TMP31:%.*]] = phi <vscale x 4 x float> [ [[TMP22]], %[[IF_TRUE3]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP13]], <vscale x 4 x float> [[TMP30]], <vscale x 4 x float> zeroinitializer
; CHECK-IC2-NEXT:    [[PREDPHI7:%.*]] = select <vscale x 4 x i1> [[TMP14]], <vscale x 4 x float> [[TMP31]], <vscale x 4 x float> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP24:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX9:%.*]] = shl i64 [[TMP24]], 4
; CHECK-IC2-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i8, ptr [[TMP23]], i64 [[DOTIDX9]]
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI]], ptr [[TMP23]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[PREDPHI7]], ptr [[TMP25]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-IC2-NEXT:    [[TMP26:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP27:%.*]] = shl i64 [[TMP26]], 2
; CHECK-IC2-NEXT:    [[TMP28:%.*]] = add i64 [[INDEX]], [[TMP27]]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT8]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP28]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[STEP_ADD]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP29:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC2-NEXT:    br i1 [[TMP29]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK-IC2:       [[EXIT]]:
; CHECK-IC2-NEXT:    ret void
;
  i64 %N, ptr %A, ptr noalias %B) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %mod = urem i64 %i, 123
  %cond = icmp eq i64 %mod, 0
  br i1 %cond, label %if.true, label %loop.latch, !prof !0

if.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.val = load float, ptr %a.addr, align 4
  %add = fadd float %a.val, %a.val
  br label %loop.latch

loop.latch:
  %val = phi float [ %add, %if.true ], [ 0.0, %loop.header ]
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  store float %val, ptr %b.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_nested_inner_uniform(
; CHECK-IC1-LABEL: define void @test_nested_inner_uniform(
; CHECK-IC1-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) #[[ATTR0]] {
; CHECK-IC1-NEXT:  [[ENTRY:.*]]:
; CHECK-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; CHECK-IC1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP3]])
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC1:       [[VECTOR_BODY]]:
; CHECK-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH7:.*]] ]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC1-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP5]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC1-NEXT:    [[TMP6:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-IC1-NEXT:    [[TMP7:%.*]] = icmp eq <vscale x 4 x i64> [[TMP6]], zeroinitializer
; CHECK-IC1-NEXT:    [[TMP8:%.*]] = xor <vscale x 4 x i1> [[TMP7]], splat (i1 true)
; CHECK-IC1-NEXT:    [[TMP9:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP8]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP11:%.*]] = getelementptr float, ptr [[C]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP11]], i32 4, <vscale x 4 x i1> [[TMP9]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP12:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP7]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP18:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP12]])
; CHECK-IC1-NEXT:    br i1 [[TMP18]], label %[[IF_TRUE1:.*]], label %[[LOOP_LATCH7]]
; CHECK-IC1:       [[IF_TRUE1]]:
; CHECK-IC1-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE_TRUE4:.*]], label %[[IF_TRUE_FALSE2:.*]]
; CHECK-IC1:       [[IF_TRUE_FALSE2]]:
; CHECK-IC1-NEXT:    [[TMP13:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP13]], i32 4, <vscale x 4 x i1> [[TMP12]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH7]]
; CHECK-IC1:       [[IF_TRUE_TRUE4]]:
; CHECK-IC1-NEXT:    [[TMP14:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD6:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP14]], i32 4, <vscale x 4 x i1> [[TMP12]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH7]]
; CHECK-IC1:       [[LOOP_LATCH7]]:
; CHECK-IC1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ], [ [[WIDE_MASKED_LOAD6]], %[[IF_TRUE_TRUE4]] ], [ [[WIDE_MASKED_LOAD4]], %[[IF_TRUE_FALSE2]] ]
; CHECK-IC1-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP9]], <vscale x 4 x float> [[WIDE_MASKED_LOAD]], <vscale x 4 x float> [[VEC_PHI]]
; CHECK-IC1-NEXT:    [[TMP15:%.*]] = fmul <vscale x 4 x float> [[PREDPHI]], [[PREDPHI]]
; CHECK-IC1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[TMP15]], ptr [[TMP16]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP4]])
; CHECK-IC1-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-IC1-NEXT:    [[TMP17:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC1-NEXT:    br i1 [[TMP17]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK-IC1:       [[EXIT]]:
; CHECK-IC1-NEXT:    ret void
;
; CHECK-IC2-LABEL: define void @test_nested_inner_uniform(
; CHECK-IC2-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP3]], 3
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP4]])
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 2
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP7]], i64 [[N]])
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH12:.*]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH12]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT17:%.*]], %[[LOOP_LATCH12]] ]
; CHECK-IC2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP8]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH12]] ]
; CHECK-IC2-NEXT:    [[STEP_ADD:%.*]] = add <vscale x 4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = urem <vscale x 4 x i64> [[STEP_ADD]], splat (i64 3)
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = icmp eq <vscale x 4 x i64> [[TMP9]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = icmp eq <vscale x 4 x i64> [[TMP10]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP13:%.*]] = xor <vscale x 4 x i1> [[TMP11]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP14:%.*]] = xor <vscale x 4 x i1> [[TMP12]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP15:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP13]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP16:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP14]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP20:%.*]] = getelementptr float, ptr [[C]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP21:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX:%.*]] = shl i64 [[TMP21]], 4
; CHECK-IC2-NEXT:    [[TMP22:%.*]] = getelementptr i8, ptr [[TMP20]], i64 [[DOTIDX]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP20]], i32 4, <vscale x 4 x i1> [[TMP15]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP22]], i32 4, <vscale x 4 x i1> [[TMP16]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP23:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP11]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP24:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP12]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP41:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP23]])
; CHECK-IC2-NEXT:    [[TMP42:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP24]])
; CHECK-IC2-NEXT:    [[TMP43:%.*]] = or i1 [[TMP41]], [[TMP42]]
; CHECK-IC2-NEXT:    br i1 [[TMP43]], label %[[IF_TRUE4:.*]], label %[[LOOP_LATCH12]]
; CHECK-IC2:       [[IF_TRUE4]]:
; CHECK-IC2-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE_TRUE8:.*]], label %[[IF_TRUE_FALSE5:.*]]
; CHECK-IC2:       [[IF_TRUE_FALSE5]]:
; CHECK-IC2-NEXT:    [[TMP25:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP26:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX18:%.*]] = shl i64 [[TMP26]], 4
; CHECK-IC2-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[TMP25]], i64 [[DOTIDX18]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD8:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP25]], i32 4, <vscale x 4 x i1> [[TMP23]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD9:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP27]], i32 4, <vscale x 4 x i1> [[TMP24]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH12]]
; CHECK-IC2:       [[IF_TRUE_TRUE8]]:
; CHECK-IC2-NEXT:    [[TMP28:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP29:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX19:%.*]] = shl i64 [[TMP29]], 4
; CHECK-IC2-NEXT:    [[TMP30:%.*]] = getelementptr i8, ptr [[TMP28]], i64 [[DOTIDX19]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD11:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP28]], i32 4, <vscale x 4 x i1> [[TMP23]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD12:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP30]], i32 4, <vscale x 4 x i1> [[TMP24]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH12]]
; CHECK-IC2:       [[LOOP_LATCH12]]:
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ], [ [[WIDE_MASKED_LOAD11]], %[[IF_TRUE_TRUE8]] ], [ [[WIDE_MASKED_LOAD8]], %[[IF_TRUE_FALSE5]] ]
; CHECK-IC2-NEXT:    [[TMP40:%.*]] = phi <vscale x 4 x float> [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[VECTOR_BODY]] ], [ [[WIDE_MASKED_LOAD12]], %[[IF_TRUE_TRUE8]] ], [ [[WIDE_MASKED_LOAD9]], %[[IF_TRUE_FALSE5]] ]
; CHECK-IC2-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP15]], <vscale x 4 x float> [[WIDE_MASKED_LOAD]], <vscale x 4 x float> [[VEC_PHI]]
; CHECK-IC2-NEXT:    [[PREDPHI16:%.*]] = select <vscale x 4 x i1> [[TMP16]], <vscale x 4 x float> [[WIDE_MASKED_LOAD4]], <vscale x 4 x float> [[TMP40]]
; CHECK-IC2-NEXT:    [[TMP31:%.*]] = fmul <vscale x 4 x float> [[PREDPHI]], [[PREDPHI]]
; CHECK-IC2-NEXT:    [[TMP32:%.*]] = fmul <vscale x 4 x float> [[PREDPHI16]], [[PREDPHI16]]
; CHECK-IC2-NEXT:    [[TMP33:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP34:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX20:%.*]] = shl i64 [[TMP34]], 4
; CHECK-IC2-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i8, ptr [[TMP33]], i64 [[DOTIDX20]]
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[TMP31]], ptr [[TMP33]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[TMP32]], ptr [[TMP35]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-IC2-NEXT:    [[TMP36:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP37:%.*]] = shl i64 [[TMP36]], 2
; CHECK-IC2-NEXT:    [[TMP38:%.*]] = add i64 [[INDEX]], [[TMP37]]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT17]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP38]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[STEP_ADD]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP39:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC2-NEXT:    br i1 [[TMP39]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK-IC2:       [[EXIT]]:
; CHECK-IC2-NEXT:    ret void
;
  i64 %N, i1 %uniform_cond, ptr %A, ptr %B, ptr %C, ptr noalias %D) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  %mod = urem i64 %i, 3
  %divergant_cond = icmp eq i64 %mod, 0
  br i1 %divergant_cond, label %if.true, label %if.false, !prof !1

if.true:
  br i1 %uniform_cond, label %if.true.true, label %if.true.false

if.true.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.load = load float, ptr %a.addr, align 4
  br label %if.true.join

if.true.false:
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %b.load = load float, ptr %b.addr, align 4
  br label %if.true.join

if.true.join:
  %a.or.b.load = phi float [ %a.load, %if.true.true ], [ %b.load, %if.true.false ]
  br label %loop.latch

if.false:
  %c.addr = getelementptr inbounds float, ptr %C, i64 %i
  %c.load = load float, ptr %c.addr, align 4
  br label %loop.latch

loop.latch:
  %load = phi float [ %a.or.b.load, %if.true.join ], [ %c.load, %if.false ]
  %mul = fmul float %load, %load
  %d.addr = getelementptr inbounds float, ptr %D, i64 %i
  store float %mul, ptr %d.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

define void @test_nested_outer_uniform(
; CHECK-IC1-LABEL: define void @test_nested_outer_uniform(
; CHECK-IC1-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) #[[ATTR0]] {
; CHECK-IC1-NEXT:  [[ENTRY:.*]]:
; CHECK-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC1-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; CHECK-IC1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP3]])
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC1-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC1:       [[VECTOR_BODY]]:
; CHECK-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH7:.*]] ]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC1-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP5]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH7]] ]
; CHECK-IC1-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE2:.*]], label %[[IF_FALSE1:.*]]
; CHECK-IC1:       [[IF_FALSE1]]:
; CHECK-IC1-NEXT:    [[TMP6:%.*]] = getelementptr float, ptr [[C]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP6]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH7]]
; CHECK-IC1:       [[IF_TRUE2]]:
; CHECK-IC1-NEXT:    [[TMP7:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-IC1-NEXT:    [[TMP8:%.*]] = icmp eq <vscale x 4 x i64> [[TMP7]], zeroinitializer
; CHECK-IC1-NEXT:    [[TMP9:%.*]] = xor <vscale x 4 x i1> [[TMP8]], splat (i1 true)
; CHECK-IC1-NEXT:    [[TMP10:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP9]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP11:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP10]])
; CHECK-IC1-NEXT:    br i1 [[TMP11]], label %[[IF_TRUE_FALSE3:.*]], label %[[IF_TRUE_TRUE5:.*]]
; CHECK-IC1:       [[IF_TRUE_FALSE3]]:
; CHECK-IC1-NEXT:    [[TMP12:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP12]], i32 4, <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP18:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD4]], [[WIDE_MASKED_LOAD4]]
; CHECK-IC1-NEXT:    br label %[[IF_TRUE_TRUE5]]
; CHECK-IC1:       [[IF_TRUE_TRUE5]]:
; CHECK-IC1-NEXT:    [[TMP19:%.*]] = phi <vscale x 4 x float> [ [[TMP18]], %[[IF_TRUE_FALSE3]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[IF_TRUE2]] ]
; CHECK-IC1-NEXT:    [[TMP13:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP8]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC1-NEXT:    [[TMP14:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    [[WIDE_MASKED_LOAD6:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP14]], i32 4, <vscale x 4 x i1> [[TMP13]], <vscale x 4 x float> poison)
; CHECK-IC1-NEXT:    [[TMP20:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD6]], [[WIDE_MASKED_LOAD6]]
; CHECK-IC1-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP10]], <vscale x 4 x float> [[TMP19]], <vscale x 4 x float> [[TMP20]]
; CHECK-IC1-NEXT:    br label %[[LOOP_LATCH7]]
; CHECK-IC1:       [[LOOP_LATCH7]]:
; CHECK-IC1-NEXT:    [[TMP15:%.*]] = phi <vscale x 4 x float> [ [[PREDPHI]], %[[IF_TRUE_TRUE5]] ], [ [[WIDE_MASKED_LOAD]], %[[IF_FALSE1]] ]
; CHECK-IC1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[INDEX]]
; CHECK-IC1-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[TMP15]], ptr [[TMP16]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP1]]
; CHECK-IC1-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP4]])
; CHECK-IC1-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-IC1-NEXT:    [[TMP17:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC1-NEXT:    br i1 [[TMP17]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK-IC1:       [[EXIT]]:
; CHECK-IC1-NEXT:    ret void
;
; CHECK-IC2-LABEL: define void @test_nested_outer_uniform(
; CHECK-IC2-SAME: i64 [[N:%.*]], i1 [[UNIFORM_COND:%.*]], ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr noalias [[D:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP3]], 3
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.usub.sat.i64(i64 [[N]], i64 [[TMP4]])
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 2
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP7]], i64 [[N]])
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-IC2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; CHECK-IC2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[LOOP_LATCH13:.*]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], %[[LOOP_LATCH13]] ]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], %[[ENTRY]] ], [ [[ACTIVE_LANE_MASK_NEXT17:%.*]], %[[LOOP_LATCH13]] ]
; CHECK-IC2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[TMP8]], %[[ENTRY]] ], [ [[VEC_IND_NEXT:%.*]], %[[LOOP_LATCH13]] ]
; CHECK-IC2-NEXT:    [[STEP_ADD:%.*]] = add <vscale x 4 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    br i1 [[UNIFORM_COND]], label %[[IF_TRUE5:.*]], label %[[IF_FALSE3:.*]]
; CHECK-IC2:       [[IF_FALSE3]]:
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = getelementptr float, ptr [[C]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX:%.*]] = shl i64 [[TMP10]], 4
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[TMP9]], i64 [[DOTIDX]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP9]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD4:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP11]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH13]]
; CHECK-IC2:       [[IF_TRUE5]]:
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = urem <vscale x 4 x i64> [[VEC_IND]], splat (i64 3)
; CHECK-IC2-NEXT:    [[TMP13:%.*]] = urem <vscale x 4 x i64> [[STEP_ADD]], splat (i64 3)
; CHECK-IC2-NEXT:    [[TMP14:%.*]] = icmp eq <vscale x 4 x i64> [[TMP12]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP15:%.*]] = icmp eq <vscale x 4 x i64> [[TMP13]], zeroinitializer
; CHECK-IC2-NEXT:    [[TMP16:%.*]] = xor <vscale x 4 x i1> [[TMP14]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP17:%.*]] = xor <vscale x 4 x i1> [[TMP15]], splat (i1 true)
; CHECK-IC2-NEXT:    [[TMP18:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP16]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP19:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP17]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP20:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP18]])
; CHECK-IC2-NEXT:    [[TMP21:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP19]])
; CHECK-IC2-NEXT:    [[TMP22:%.*]] = or i1 [[TMP20]], [[TMP21]]
; CHECK-IC2-NEXT:    br i1 [[TMP22]], label %[[IF_TRUE_FALSE6:.*]], label %[[IF_TRUE_TRUE9:.*]]
; CHECK-IC2:       [[IF_TRUE_FALSE6]]:
; CHECK-IC2-NEXT:    [[TMP23:%.*]] = getelementptr float, ptr [[B]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP24:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX18:%.*]] = shl i64 [[TMP24]], 4
; CHECK-IC2-NEXT:    [[TMP25:%.*]] = getelementptr i8, ptr [[TMP23]], i64 [[DOTIDX18]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD7:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP23]], i32 4, <vscale x 4 x i1> [[TMP18]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD8:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP25]], i32 4, <vscale x 4 x i1> [[TMP19]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP40:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD7]], [[WIDE_MASKED_LOAD7]]
; CHECK-IC2-NEXT:    [[TMP41:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD8]], [[WIDE_MASKED_LOAD8]]
; CHECK-IC2-NEXT:    br label %[[IF_TRUE_TRUE9]]
; CHECK-IC2:       [[IF_TRUE_TRUE9]]:
; CHECK-IC2-NEXT:    [[TMP42:%.*]] = phi <vscale x 4 x float> [ [[TMP40]], %[[IF_TRUE_FALSE6]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[IF_TRUE5]] ]
; CHECK-IC2-NEXT:    [[TMP43:%.*]] = phi <vscale x 4 x float> [ [[TMP41]], %[[IF_TRUE_FALSE6]] ], [ shufflevector (<vscale x 4 x float> insertelement (<vscale x 4 x float> poison, float poison, i64 0), <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer), %[[IF_TRUE5]] ]
; CHECK-IC2-NEXT:    [[TMP26:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i1> [[TMP14]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP27:%.*]] = select <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i1> [[TMP15]], <vscale x 4 x i1> zeroinitializer
; CHECK-IC2-NEXT:    [[TMP28:%.*]] = getelementptr float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP29:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX19:%.*]] = shl i64 [[TMP29]], 4
; CHECK-IC2-NEXT:    [[TMP30:%.*]] = getelementptr i8, ptr [[TMP28]], i64 [[DOTIDX19]]
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD11:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP28]], i32 4, <vscale x 4 x i1> [[TMP26]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[WIDE_MASKED_LOAD12:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr [[TMP30]], i32 4, <vscale x 4 x i1> [[TMP27]], <vscale x 4 x float> poison)
; CHECK-IC2-NEXT:    [[TMP44:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD11]], [[WIDE_MASKED_LOAD11]]
; CHECK-IC2-NEXT:    [[TMP45:%.*]] = fmul <vscale x 4 x float> [[WIDE_MASKED_LOAD12]], [[WIDE_MASKED_LOAD12]]
; CHECK-IC2-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP18]], <vscale x 4 x float> [[TMP42]], <vscale x 4 x float> [[TMP44]]
; CHECK-IC2-NEXT:    [[PREDPHI12:%.*]] = select <vscale x 4 x i1> [[TMP19]], <vscale x 4 x float> [[TMP43]], <vscale x 4 x float> [[TMP45]]
; CHECK-IC2-NEXT:    br label %[[LOOP_LATCH13]]
; CHECK-IC2:       [[LOOP_LATCH13]]:
; CHECK-IC2-NEXT:    [[TMP31:%.*]] = phi <vscale x 4 x float> [ [[PREDPHI]], %[[IF_TRUE_TRUE9]] ], [ [[WIDE_MASKED_LOAD]], %[[IF_FALSE3]] ]
; CHECK-IC2-NEXT:    [[TMP32:%.*]] = phi <vscale x 4 x float> [ [[PREDPHI12]], %[[IF_TRUE_TRUE9]] ], [ [[WIDE_MASKED_LOAD4]], %[[IF_FALSE3]] ]
; CHECK-IC2-NEXT:    [[TMP33:%.*]] = getelementptr inbounds float, ptr [[D]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP34:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[DOTIDX20:%.*]] = shl i64 [[TMP34]], 4
; CHECK-IC2-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i8, ptr [[TMP33]], i64 [[DOTIDX20]]
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[TMP31]], ptr [[TMP33]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-IC2-NEXT:    call void @llvm.masked.store.nxv4f32.p0(<vscale x 4 x float> [[TMP32]], ptr [[TMP35]], i32 4, <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-IC2-NEXT:    [[TMP36:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP37:%.*]] = shl i64 [[TMP36]], 2
; CHECK-IC2-NEXT:    [[TMP38:%.*]] = add i64 [[INDEX]], [[TMP37]]
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[ACTIVE_LANE_MASK_NEXT17]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP38]], i64 [[TMP5]])
; CHECK-IC2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[STEP_ADD]], [[BROADCAST_SPLAT]]
; CHECK-IC2-NEXT:    [[TMP39:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-IC2-NEXT:    br i1 [[TMP39]], label %[[VECTOR_BODY]], label %[[EXIT:.*]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK-IC2:       [[EXIT]]:
; CHECK-IC2-NEXT:    ret void
;
  i64 %N, i1 %uniform_cond, ptr %A, ptr %B, ptr %C, ptr noalias %D) {
entry:
  br label %loop.header

loop.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop.latch ]
  br i1 %uniform_cond, label %if.true, label %if.false

if.true:
  %mod = urem i64 %i, 3
  %divergant_cond = icmp eq i64 %mod, 0
  br i1 %divergant_cond, label %if.true.true, label %if.true.false, !prof !1

if.true.true:
  %a.addr = getelementptr inbounds float, ptr %A, i64 %i
  %a.load = load float, ptr %a.addr, align 4
  %a.val = fmul float %a.load, %a.load
  br label %if.true.join

if.true.false:
  %b.addr = getelementptr inbounds float, ptr %B, i64 %i
  %b.load = load float, ptr %b.addr, align 4
  %b.val = fmul float %b.load, %b.load
  br label %if.true.join

if.true.join:
  %a.or.b.val = phi float [ %a.val, %if.true.true ], [ %b.val, %if.true.false ]
  br label %loop.latch

if.false:
  %c.addr = getelementptr inbounds float, ptr %C, i64 %i
  %c.load = load float, ptr %c.addr, align 4
  br label %loop.latch

loop.latch:
  %val = phi float [ %a.or.b.val, %if.true.join ], [ %c.load, %if.false ]
  %d.addr = getelementptr inbounds float, ptr %D, i64 %i
  store float %val, ptr %d.addr, align 4
  %i.next = add nuw i64 %i, 1
  %cmp = icmp eq i64 %i.next, %N
  br i1 %cmp, label %exit, label %loop.header

exit:
  ret void
}

!0 = !{!"branch_weights", i32 1, i32 1000}
!1 = !{!"branch_weights", i32 1000, i32 1}
;.
; CHECK-IC1: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK-IC1: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK-IC1: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK-IC1: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
; CHECK-IC1: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK-IC1: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]], [[META2]]}
; CHECK-IC1: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; CHECK-IC1: [[LOOP7]] = distinct !{[[LOOP7]], [[META1]], [[META2]]}
;.
; CHECK-IC2: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK-IC2: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK-IC2: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK-IC2: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
; CHECK-IC2: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK-IC2: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]], [[META2]]}
; CHECK-IC2: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; CHECK-IC2: [[LOOP7]] = distinct !{[[LOOP7]], [[META1]], [[META2]]}
;.
